// packages/ui/spike/solid/src/components/button/UIButton.tsx
import { Show, createEffect, createMemo, untrack } from "solid-js"
import { isServer, type JSX } from "@solidjs/web"

import { proto } from "$/util"
import { Icons, type IconData } from "$/icons"
import { buttonVocabulary } from "$/components/button/button.vocabulary.en"

import { Cell } from "$spike/Cell"
import { FormHost } from "$spike/FormHost"
import { SlotContent } from "$spike/SlotContent"
import { UIElement } from "$spike/UIElement"
import type { AttributeName } from "$spike/spike.types"

import buttonCSS from "$/components/button/button.css?inline"

/****************
 * ### `<ui-button>`
 * A button:  a semantic `<button>` (or `<a>` with `href`) in the shadow root, in Fomantic's class grammar.
 * - Form-associated (`FormHost`) only so `type=submit|reset` can reach `internals.form`;  it submits no value
 *   of its own except while it is the submitter (see `submit()`).
 * - `active` is auto-controlled:  `toggle` flips it on click and dispatches `ui-toggle` first.
 * - Icons come from `Icons` asynchronously;  the `.icon` box is sized by CSS, so the SVG arriving shifts nothing.
 ****************/
export class UIButton extends UIElement<typeof buttonVocabulary> {
  @proto static vocabulary = buttonVocabulary
  @proto static styles = { button: buttonCSS }
  @proto static Host = FormHost

  /** `active`:  host-controlled, or toggled internally. */
  readonly active = this.controlled("active", false)

  /** Light-DOM slot occupancy. */
  readonly slots = new SlotContent(this.host)

  /** Disabled by a `<fieldset disabled>`. */
  readonly formDisabled = new Cell((this.host as FormHost).formDisabled)

  /** Loaded icon data for the `icon` attribute;  starts from the cache, so a known icon draws at once. */
  private readonly iconData = new Cell<IconData | undefined>(
    untrack(() => (this.attrs.icon ? Icons.peek(this.attrs.icon) : undefined))
  )

  /** Host `aria-label`, forwarded to the inner control (an icon-only button's name). */
  private readonly ariaLabel = new Cell(this.host.getAttribute(ARIA_LABEL))

  /** The inner `<button>` / `<a>`. */
  private control?: HTMLElement

  /** Icon name last asked for. */
  private iconName?: string

  constructor(...args: ConstructorParameters<typeof UIElement>) {
    super(...args)
    createEffect(
      () => this.attrs.icon,
      (name) => void this.loadIcon(name)
    )
    if (isServer) return
    const observer = new MutationObserver(() => this.ariaLabel.set(this.host.getAttribute(ARIA_LABEL)))
    observer.observe(this.host, { attributeFilter: [ARIA_LABEL] })
    this.host.addReleaseCallback(() => observer.disconnect())
  }

  ////////////////
  // ## Derived state
  ////////////////

  /** Has text content (slotted, or the `content` shorthand)? */
  readonly hasText = createMemo(() => this.slots.has("") || !!this.attrs.content)

  /** Has an icon (attribute or `icon` slot)? */
  readonly hasIcon = createMemo(() => !!this.attrs.icon || this.slots.has(this.slot("icon")))

  /** Has a joined label (attribute or `label` slot)? */
  readonly hasLabel = createMemo(() => !!this.attrs.label || this.slots.has(this.slot("label")))

  /** SVG for the `icon` attribute. */
  readonly iconSvg = createMemo(() => {
    const data = this.iconData.get()
    return data ? Icons.svg(data) : undefined
  })

  isDisabled(): boolean {
    return this.attrs.disabled || this.formDisabled.get()
  }

  protected classValue(name: AttributeName<typeof buttonVocabulary>): unknown {
    if (name === "active") return this.active.get()
    if (name === "disabled") return this.isDisabled()
    // with a joined label, `labeled` goes on the wrapper, not the inner button
    if (name === "labeled" && this.hasLabel()) return false
    return super.classValue(name)
  }

  /** `icon` for icon-only buttons and for `labeled icon` buttons. */
  protected extraClasses(): string | undefined {
    if (!this.hasIcon() || this.attrs.animated) return undefined
    const labeledIcon = !!this.attrs.labeled && !this.hasLabel()
    return !this.hasText() || labeledIcon ? ICON_CLASS : undefined
  }

  protected hostStates() {
    const { attached, floated } = this.attrs
    return {
      active: this.active.get(),
      disabled: this.isDisabled(),
      loading: this.attrs.loading,
      fluid: this.attrs.fluid || attached === true || attached === "top" || attached === "bottom",
      "left-floated": floated === "left",
      "right-floated": floated === "right"
    }
  }

  ////////////////
  // ## Rendering
  ////////////////

  render(): JSX.Element {
    return (
      <Show when={this.hasLabel()} fallback={this.control_()}>
        <div
          class={this.buildClasses({
            size: this.attrs.size,
            color: this.attrs.color,
            labeled: this.attrs.labeled || true
          })}
        >
          {this.control_()}
          <span class="ui basic label" part={this.part("label")}>
            <slot name={this.slot("label")}>{this.attrs.label}</slot>
          </span>
        </div>
      </Show>
    )
  }

  /** The inner `<button>`, or `<a>` with `href`. */
  private control_(): JSX.Element {
    const content = () => this.content()
    return (
      <Show
        when={this.attrs.href}
        fallback={
          <button
            ref={(element) => (this.control = element)}
            type="button"
            class={this.classes()}
            part={this.part("button")}
            disabled={this.isDisabled()}
            aria-pressed={this.attrs.toggle ? (this.active.get() ? "true" : "false") : undefined}
            aria-busy={this.attrs.loading ? "true" : undefined}
            aria-label={this.ariaLabel.get() ?? undefined}
            onClick={this.onClick}
          >
            {content()}
          </button>
        }
      >
        <a
          ref={(element) => (this.control = element)}
          class={this.classes()}
          part={this.part("button")}
          href={this.isDisabled() ? undefined : this.attrs.href}
          target={this.attrs.target}
          role={this.isDisabled() ? "link" : undefined}
          aria-disabled={this.isDisabled() ? "true" : undefined}
          aria-busy={this.attrs.loading ? "true" : undefined}
          aria-label={this.ariaLabel.get() ?? undefined}
          onClick={this.onClick}
        >
          {content()}
        </a>
      </Show>
    )
  }

  /** Icon + text, or the two `.content` boxes of an `animated` button. */
  private content(): JSX.Element {
    const text = <slot>{this.attrs.content}</slot>
    return (
      <Show when={this.attrs.animated} fallback={[<Show when={this.hasIcon()}>{this.icon()}</Show>, text]}>
        <span class="visible content">{text}</span>
        <span class="hidden content">{this.icon()}</span>
      </Show>
    )
  }

  /** The icon box:  the `icon` slot, falling back to the `icon` attribute's SVG. */
  private icon(): JSX.Element {
    return (
      <span class={ICON_CLASS} part={this.part("icon")}>
        <slot name={this.slot("icon")}>{this.iconSvg()}</slot>
      </span>
    )
  }

  ////////////////
  // ## Behaviour
  ////////////////

  /** Click:  toggle, then submit / reset the form for those types. */
  private readonly onClick = (event: MouseEvent) => {
    if (this.isDisabled()) {
      event.preventDefault()
      return
    }
    if (this.attrs.toggle) {
      const next = !this.active.get()
      this.active.request(next, () => this.emit("ui-toggle", { active: next, originalEvent: event }))
    }
    const { form } = this.host.internals
    if (!form) return
    if (this.attrs.type === "submit") this.submit(form)
    else if (this.attrs.type === "reset") form.reset()
  }

  /**
   * `form.requestSubmit()`, with this button's `name=value` in the submission.
   * - A custom element can't be `requestSubmit()`'s submitter (it throws), so the button sets its own form
   *   value for the duration of the synchronous submit algorithm, then clears it.
   */
  private submit(form: HTMLFormElement) {
    const { name, value } = this.attrs
    const { internals } = this.host
    if (name) internals.setFormValue(value ?? "")
    try {
      form.requestSubmit()
    } finally {
      if (name) internals.setFormValue(null)
    }
  }

  /** Load the icon's data;  a later name wins over an earlier, slower one. */
  private async loadIcon(name: string | undefined) {
    this.iconName = name
    const data = name ? await Icons.get(name) : undefined
    if (this.iconName === name) this.iconData.set(data)
  }

  /** Host callback:  fieldset disabled changed. */
  onFormDisabled(disabled: boolean) {
    this.formDisabled.set(disabled)
  }

  /** Focus the inner control. */
  focus() {
    this.control?.focus()
  }
}

/** Grammar words the element adds itself (not attributes):  the `icon` class / box. */
const ICON_CLASS = "icon"

/** Host attribute forwarded to the inner control. */
const ARIA_LABEL = "aria-label"

// packages/ui/spike/lit/src/components/button/UIButton.ts
import { html, nothing, type PropertyValues, type TemplateResult } from "lit"
import { property } from "lit/decorators.js"
import { ifDefined } from "lit/directives/if-defined.js"

import { proto } from "$/util"
import { Shorthand } from "$/elements"
import { buttonVocabulary } from "$/components/button/button.vocabulary.en"
import type { ButtonToggleDetail } from "$/components/components.types"
import { IconRenderer, UIElement } from "../../elements"

import buttonCSS from "$/components/button/button.css?inline"

/****************
 * ### `<ui-button>`
 * A semantic `<button>` (or `<a>` with `href`) in Fomantic's class grammar:  `<button class="ui primary button">`.
 * - Shorthand:  `icon` (name, or `{ name }`), `label` (joined label), `content` (text, property only --
 *   `button.vocabulary.en.ts` has no `content` attribute).  Slotted content wins over shorthand.
 * - `label` wraps the button in `<div class="ui labeled button">`;  size / colour go on that wrapper so the
 *   button AND the label pick them up.
 * - `toggle`:  click flips `active` (controlled:  `ui-toggle` first, host may revert), `aria-pressed`.
 * - `type="submit" | "reset"`:  the inner button can't reach the outer form, so the element is form-associated
 *   and calls `internals.form.requestSubmit()` / `reset()`.  `name` / `value` submit through a transient
 *   `setFormValue()` around `requestSubmit()`.
 * - `disabled`:  real `disabled` on the inner button (`aria-disabled` on a link), and a capture listener
 *   swallows clicks on the host.
 ****************/
export class UIButton extends UIElement.for(buttonVocabulary) {
  static formAssociated = true
  @proto static delegatesFocus = true
  @proto static sheets = [[buttonVocabulary.noun, buttonCSS]] as const

  /** Text shorthand;  the default slot wins.  Property only:  the vocabulary has no `content` attribute. */
  @property({ attribute: false }) accessor content: string | undefined = undefined

  /** `<fieldset disabled>` disabled us. */
  private formDisabled = false

  /** icon templates */
  private readonly icons = new IconRenderer(this)

  constructor() {
    super()
    this.addEventListener("click", this.onHostClick, { capture: true })
  }

  /** Also watch the host's `aria-label`, forwarded to the inner button (an icon-only button's name). */
  static override get observedAttributes() {
    return [...super.observedAttributes, ARIA_LABEL]
  }

  override attributeChangedCallback(name: string, old: string | null, value: string | null) {
    if (name === ARIA_LABEL) this.requestUpdate()
    else super.attributeChangedCallback(name, old, value)
  }

  ////////////////
  // ## Rendering
  ////////////////

  protected override willUpdate(changed: PropertyValues) {
    super.willUpdate(changed)
    const { attached, floated } = this
    this.setState("active", this.active)
    this.setState("disabled", this.isDisabled)
    this.setState("loading", this.loading)
    this.setState("fluid", this.fluid || attached === true || attached === "top" || attached === "bottom")
    this.setState("left-floated", floated === "left")
    this.setState("right-floated", floated === "right")
  }

  protected override render() {
    const label = this.hasLabel()
    if (!label) return this.renderButton(this.classes(this.iconClass()))
    const side = this.labeled === "left" ? "left" : true
    const wrapper = this.classes(undefined, { ...this.onlyKinds(WRAPPER_KINDS), labeled: side })
    const inner = this.classes(this.iconClass(), { ...this.withoutKinds(WRAPPER_KINDS), labeled: false })
    return html`<div class=${wrapper}>
      ${this.renderButton(inner)}<span class="ui basic label" part=${this.partName("label")}
        ><slot name=${this.slotName("label")} @slotchange=${this.onSlotChange}>${this.label}</slot></span
      >
    </div>`
  }

  /** The `<button>` or `<a>` itself. */
  private renderButton(classes: string) {
    const disabled = this.isDisabled
    const content = this.renderContent()
    const ariaLabel = this.getAttribute(ARIA_LABEL) ?? undefined
    if (this.href) {
      return html`<a
        class=${classes}
        part=${this.partName("button")}
        href=${ifDefined(disabled ? undefined : this.href)}
        target=${ifDefined(this.target)}
        role=${ifDefined(disabled ? "link" : undefined)}
        aria-disabled=${ifDefined(disabled ? "true" : undefined)}
        aria-label=${ifDefined(ariaLabel)}
        aria-busy=${ifDefined(this.loading ? "true" : undefined)}
        @click=${this.onClick}
        >${content}</a
      >`
    }
    return html`<button
      class=${classes}
      part=${this.partName("button")}
      type="button"
      ?disabled=${disabled}
      aria-label=${ifDefined(ariaLabel)}
      aria-pressed=${ifDefined(this.toggle ? String(this.active) : undefined)}
      aria-busy=${ifDefined(this.loading ? "true" : undefined)}
      @click=${this.onClick}
    >
      ${content}
    </button>`
  }

  /** Icon + text, or the two faces of an `animated` button. */
  private renderContent(): TemplateResult {
    const text = html`<slot @slotchange=${this.onSlotChange}>${this.content ?? nothing}</slot>`
    const icon = this.renderIcon()
    if (this.animated) {
      return html`<span class="visible content">${text}</span><span class="hidden content">${icon}</span>`
    }
    return html`${icon}${text}`
  }

  /**
   * `<span class="icon">` around the icon slot / shorthand, or a bare slot waiting for content.
   * - HACK: the shorthand svg is a SIBLING of the slot, not its fallback content as `button.css`'s contract
   *   says:  the sheet sizes `.icon > svg` and `.icon > ::slotted(svg)`, and fallback content inside `<slot>`
   *   matches neither, so a labeled-icon glyph filled its whole block.
   */
  private renderIcon() {
    const slot = this.slotName("icon")
    if (!this.hasIcon()) return html`<slot name=${slot} @slotchange=${this.onSlotChange}></slot>`
    const svg = this.slotted("icon").length ? nothing : this.icons.template(this.iconName())
    return html`<span class="icon" part=${this.partName("icon")}
      >${svg}<slot name=${slot} @slotchange=${this.onSlotChange}></slot
    ></span>`
  }

  ////////////////
  // ## Content detection
  ////////////////

  /** Icon name from the `icon` shorthand. */
  private iconName(): string | undefined {
    const props = Shorthand.resolve(this.icon, Shorthand.map.name)
    return typeof props?.name === "string" ? props.name : undefined
  }

  /** `icon` for an icon-only button;  `labeled` + icon makes `labeled icon`. */
  private iconClass(): string | undefined {
    if (!this.hasIcon() || this.animated) return undefined
    return !this.hasText() || (this.labeled && !this.hasLabel()) ? ICON_CLASS : undefined
  }

  private hasIcon(): boolean {
    return !!this.iconName() || this.slotted("icon").length > 0
  }

  private hasLabel(): boolean {
    return (this.label !== undefined && this.label !== "") || this.slotted("label").length > 0
  }

  /** Default-slot content (or `content`) that isn't whitespace. */
  private hasText(): boolean {
    if (this.content) return true
    // SSR:  the DOM shim has no `childNodes`
    for (const node of this.childNodes ?? []) {
      if (node.nodeType === Node.TEXT_NODE && node.textContent?.trim()) return true
      if (node instanceof Element && !node.slot) return true
    }
    return false
  }

  /** A slot's assignment changed:  icon / text / label presence may have too. */
  private readonly onSlotChange = () => this.requestUpdate()

  /** Overrides keeping only attributes of `kinds` (everything else `undefined`). */
  private onlyKinds(kinds: ReadonlySet<string>) {
    return this.filterKinds((kind) => !kinds.has(kind))
  }

  /** Overrides dropping attributes of `kinds`. */
  private withoutKinds(kinds: ReadonlySet<string>) {
    return this.filterKinds((kind) => kinds.has(kind))
  }

  /** `{ [attribute]: undefined }` for every attribute whose kind `drop` accepts. */
  private filterKinds(drop: (kind: string) => boolean) {
    const overrides: Record<string, undefined> = {}
    for (const spec of this.vocabulary.attributes) if (drop(spec.kind)) overrides[spec.name] = undefined
    return overrides
  }

  ////////////////
  // ## Behaviour
  ////////////////

  /** Disabled by attribute or by a disabled fieldset. */
  get isDisabled(): boolean {
    return this.disabled || this.formDisabled
  }

  /** Swallow clicks while disabled, before any other listener on the host. */
  private readonly onHostClick = (event: Event) => {
    if (!this.isDisabled) return
    event.preventDefault()
    event.stopImmediatePropagation()
  }

  /** Toggle, submit or reset. */
  private readonly onClick = (event: MouseEvent) => {
    if (this.isDisabled || this.loading) return
    if (this.toggle) {
      const detail: ButtonToggleDetail = { active: !this.active, originalEvent: event }
      this.transition("active", !this.active, "ui-toggle", detail)
    }
    const form = this.internals.form
    if (!form) return
    if (this.type === "submit") this.submit(form)
    else if (this.type === "reset") form.reset()
  }

  /**
   * `requestSubmit()`, contributing `name=value` for the duration only -- a form-associated element can't be
   * the `submitter`, but its form value is read synchronously while the submit event builds `FormData`.
   */
  private submit(form: HTMLFormElement) {
    const named = !!this.name
    if (named) this.internals.setFormValue(this.value ?? "")
    try {
      form.requestSubmit()
    } finally {
      if (named) this.internals.setFormValue(null)
    }
  }

  /** Called by the browser when an ancestor fieldset toggles disabled. */
  formDisabledCallback(disabled: boolean) {
    this.formDisabled = disabled
    this.requestUpdate()
  }
}

/** Kinds that style the labeled wrapper rather than the inner button. */
const WRAPPER_KINDS: ReadonlySet<string> = new Set(["size", "color"])

/** `ClassBuilder` extra for icon-only / labeled icon buttons -- grammar, not vocabulary. */
const ICON_CLASS = "icon"

/** Platform attribute forwarded to the inner button. */
const ARIA_LABEL = "aria-label"
