// packages/ui/spike/solid/src/components/parts/UIAvatar.tsx
import { Show } from "solid-js"
import type { JSX } from "@solidjs/web"

import { proto } from "$spike/core"
import { avatarVocabulary } from "$/components/parts/parts.vocabulary.en"

import { PartElement } from "./PartElement"

/****************
 * ### `<ui-avatar>`
 * A small picture of a person:  `<span class="avatar"><img part="image" alt=""></span>` from `src`, else the
 * default slot (a slotted `<img>`).
 * - `alt` defaults to `""`:  the person's name is almost always right next to it.
 ****************/
export class UIAvatar extends PartElement<typeof avatarVocabulary> {
  @proto static vocabulary = avatarVocabulary

  protected tag(): string {
    return "span"
  }

  protected content(): JSX.Element {
    return (
      <Show when={this.attrs.src} fallback={<slot />}>
        <img src={this.attrs.src} alt={this.attrs.alt ?? ""} part={this.part("image")} />
      </Show>
    )
  }
}

// packages/ui/spike/lit/src/components/parts/UIAvatar.ts
import { html, nothing } from "lit"

import { proto } from "../../core"
import { avatarVocabulary } from "$/components/parts/parts.vocabulary.en"
import { PartElement } from "./PartElement"

/****************
 * ### `<ui-avatar>`
 * A small picture of a person:  `<span class="avatar"><img alt="">` from `src`, or a slotted `<img>`.
 * - `alt` defaults to `""`:  the person's name is right beside it, so the picture is decorative.
 ****************/
export class UIAvatar extends PartElement.for(avatarVocabulary) {
  @proto static box = "span" as const

  protected override renderContent() {
    const image = this.src
      ? html`<img part=${this.partName("image")} src=${this.src} alt=${this.alt ?? ""} />`
      : nothing
    return html`${image}<slot></slot>`
  }
}
