// packages/ui/src/components/ui-segment/UISegment.tsx
import { Show, createEffect } from "solid-js"
import type { JSX } from "@solidjs/web"

import { PART_OWNER_TOKENS, proto, UIElement } from "$/ui/core"

import { segmentVocabulary } from "./ui-segment.vocabulary.en"
import { SegmentFallback } from "./ui-segment.fallback"

import segmentCSS from "./ui-segment.css?inline"
import { TRUE, VISUALLY_HIDDEN, STATUS } from "$/ui/components/components.types"

/****************
 * ### `<ui-segment>`
 * A segment:  `<div class="ui … segment" part="segment"><slot></slot></div>`.
 * - OWNER side:  declares `--ui-inverted` on its root, default included (`0`), so parts inside a plain segment
 *   nested in an inverted one don't inherit the outer segment's `1` (`ui-parts.css` "Owner tokens").  Inline only
 *   when `inverted` (`1`):  the sheet declares the `0`, or `1` for a member of an `<ui-segments inverted>`, which an
 *   inline `0` would beat.  `inverted` itself (`color-scheme: dark`) comes from `ui-segment.css`.
 * - `:state(piled)`:  the host becomes the stacking context the rotated sheets sit behind.
 * - `scrolling`:  the root is a keyboard stop (`tabindex=0`), as every scrollable region must be.
 * - `loading`:  `aria-busy` (internals) and a visually hidden `role=status` "Loading…";  `disabled`:
 *   `aria-disabled`.
 ****************/
export class UISegment extends UIElement<typeof segmentVocabulary> {
  @proto static vocabulary = segmentVocabulary
  @proto static styles = { segment: segmentCSS }
  @proto static Fallback = SegmentFallback

  constructor(...args: ConstructorParameters<typeof UIElement>) {
    super(...args)
    const { internals } = this.host
    createEffect(
      () => [this.attrs.loading, this.attrs.disabled] as const,
      ([loading, disabled]) => {
        internals.ariaBusy = loading ? TRUE : null
        internals.ariaDisabled = disabled ? TRUE : null
      }
    )
  }

  protected hostStates() {
    const { piled, inverted, loading, disabled } = this.attrs
    return { piled, inverted, loading, disabled }
  }

  render(): JSX.Element {
    return (
      <div
        class={this.classes()}
        part={this.part("segment")}
        tabindex={this.attrs.scrolling ? 0 : undefined}
        style={this.attrs.inverted ? { [PART_OWNER_TOKENS.inverted]: "1" } : undefined}
      >
        <slot />
        <Show when={this.attrs.loading}>
          <span class={VISUALLY_HIDDEN} role={STATUS}>
            {this.text("loading")}
          </span>
        </Show>
      </div>
    )
  }
}

// packages/ui/spike/lit/src/components/segment/UISegment.ts
import { html, nothing, type PropertyValues } from "lit"
import { ifDefined } from "lit/directives/if-defined.js"

import { proto, PART_OWNER_TOKENS, UIElement } from "../../core"
import { segmentVocabulary } from "$/components/segment/segment.vocabulary.en"
import { SegmentFallback } from "$/components/segment/segment.fallback"

import segmentCSS from "$/components/segment/segment.css?inline"

/****************
 * ### `<ui-segment>`
 * A grouping of content:  `<div class="ui ... segment" part="segment"><slot>`, host `display: contents`.
 * - OWNER tokens:  the root declares `--ui-inverted` INLINE, `0` or `1`, default included, so a plain segment
 *   inside an inverted one doesn't hand its parts the outer value.  `segment.css` adds `color-scheme: dark`
 *   (and sets `1` again) on an inverted root;  a plain one inherits the scheme, as the sheet documents.
 * - States:  `:state(piled)` makes the host the stacking context of the rotated sheets;  `inverted`,
 *   `loading`, `disabled` are for page styling.
 * - `loading`:  `aria-busy` on the host and a visually hidden `role=status` "Loading…" (`UI.i18n`).
 * - `disabled`:  the root is `inert`, so slotted controls can't be focused or clicked.
 * - `scrolling`:  the root is focusable (`tabindex="0"`), so keyboard users can scroll it.
 ****************/
export class UISegment extends UIElement.for(segmentVocabulary) {
  @proto static sheets = [[segmentVocabulary.noun, segmentCSS]] as const
  @proto static Fallback = SegmentFallback

  protected override willUpdate(changed: PropertyValues) {
    super.willUpdate(changed)
    this.setState("piled", this.piled)
    this.setState("inverted", this.inverted)
    this.setState("loading", this.loading)
    this.setState("disabled", this.disabled)
    this.internals.ariaBusy = this.loading ? "true" : null
  }

  protected override render() {
    const status = this.loading
      ? html`<span class="ui-visually-hidden-force" role="status">${this.t("loading")}</span>`
      : nothing
    return html`<div
      class=${this.classes()}
      part=${this.partName("segment")}
      style=${`${PART_OWNER_TOKENS.inverted}: ${this.inverted ? 1 : 0}`}
      tabindex=${ifDefined(this.scrolling ? "0" : undefined)}
      ?inert=${this.disabled}
    >
      <slot></slot>${status}
    </div>`
  }
}
