// packages/ui/spike/solid/peers.ts
/**
 * Every peer specifier the Solid spike's `dist/` imports, one namespace re-export each.
 * - `yarn vendor` builds one file per line (`vendor/`, for import-map pages) -- ONE build, so `solid-js` exists
 *   once and `@spell/solid-element` / `@solidjs/web` link to that copy;  `yarn measure` bundles this file once as
 *   the `library` tier.  `SpikeMeasure`'s `peersMissing` check flags a specifier `dist/` needs but this list lacks.
 */

export * as solidJs from "solid-js"
export * as web from "@solidjs/web"
export * as element from "@spell/solid-element"

// packages/ui/spike/lit/peers.ts
/**
 * Every `lit` specifier the Lit spike's `dist/` imports, one namespace re-export each.
 * - `yarn vendor` builds one file per line (`vendor/`, for import-map pages);  `yarn measure` bundles this file
 *   once as the `library` tier.  `SpikeMeasure`'s `peersMissing` check flags a specifier `dist/` needs but
 *   this list lacks.
 */

export * as lit from "lit"
export * as decorators from "lit/decorators.js"
export * as ifDefined from "lit/directives/if-defined.js"
export * as live from "lit/directives/live.js"
export * as repeat from "lit/directives/repeat.js"
export * as staticHtml from "lit/static-html.js"
