// packages/ui/spike/lit/src/components/label/UILabel.ts
import { html, nothing, type PropertyValues, type TemplateResult } from "lit"
import { ifDefined } from "lit/directives/if-defined.js"

import { proto, type LabelRemoveDetail, IconRenderer, OwnerController, PARTS_SHEET, UIElement } from "../../core"
import { labelVocabulary } from "$/components/label/label.vocabulary.en"
import { LabelFallback } from "$/components/label/label.fallback"

import labelCSS from "$/components/label/label.css?inline"

/****************
 * ### `<ui-label>`
 * A label:  `<span class="ui ... label" part="label">` (`<a>` with `href`), host `display: contents`, holding in
 * order `img.image`, `span.icon`, the default slot, `span.detail`, and a `removable` label's delete button.
 * - `image`:  a string attribute.  Present (bare / `""`) => class `image` around a slotted `<img>`;  a non-empty
 *   value is the `src` of the label's own `img.image`.  `ClassBuilder` emits nothing for a string kind, so the
 *   `image` class goes in as `extra`.
 * - `icon` class (ClassBuilder `extra`) when there's an icon and no text:  the icon centres.
 * - `removable`:  `button.delete.icon` dispatches the cancelable `ui-remove` (`LabelRemoveDetail`);  the
 *   element never removes itself -- the host decides.
 * - A host `aria-label` is forwarded onto the root (an icon-only label);  a `<span>` root then becomes
 *   `role=img`, since `aria-label` is prohibited on a generic element.
 * - Inside a statistic (an owner whose `ownsParts` lists `label`) it IS that statistic's label part:
 *   `<div class="label" part="label">`, `:state(in-statistic)`, and it adopts `parts.css` by name.
 ****************/
export class UILabel extends UIElement.for(labelVocabulary) {
  @proto static sheets = [[labelVocabulary.noun, labelCSS]] as const
  @proto static Fallback = LabelFallback
  @proto static forwardsAriaLabel = true

  /** icon templates */
  private readonly icons = new IconRenderer(this)

  /** a statistic owning this label as its part */
  protected readonly statistic = new OwnerController(this, labelVocabulary.noun, {
    onChange: () => this.adoptSheets()
  })

  protected override willUpdate(changed: PropertyValues) {
    super.willUpdate(changed)
    this.setState("active", this.active)
    this.setState("disabled", this.disabled)
  }

  /** Also adopt `parts.css` while owned by a statistic. */
  protected override sheetNames(): string[] {
    const names = super.sheetNames()
    return this.statistic.owner ? [...names, PARTS_SHEET] : names
  }

  protected override render() {
    if (this.statistic.owner) {
      return html`<div class=${labelVocabulary.noun} part=${this.partName("label")}><slot></slot></div>`
    }
    const icon = this.hasIcon()
    const extra = [this.image === undefined ? "" : IMAGE_CLASS, icon && !this.hasText() ? ICON_CLASS : ""]
    const classes = this.classes(extra.filter(Boolean).join(" ") || undefined)
    const content = this.renderContent(icon)
    const ariaLabel = this.ariaLabelled()
    if (this.href) {
      return html`<a
        class=${classes}
        part=${this.partName("label")}
        href=${ifDefined(this.disabled ? undefined : this.href)}
        target=${ifDefined(this.target)}
        role=${ifDefined(this.disabled ? "link" : undefined)}
        aria-disabled=${ifDefined(this.disabled ? "true" : undefined)}
        aria-label=${ifDefined(ariaLabel)}
        >${content}</a
      >`
    }
    return html`<span
      class=${classes}
      part=${this.partName("label")}
      role=${ifDefined(ariaLabel ? "img" : undefined)}
      aria-label=${ifDefined(ariaLabel)}
      >${content}</span
    >`
  }

  /** Image, icon, text, detail, delete button -- in the contract's order. */
  private renderContent(icon: boolean): TemplateResult {
    const image = this.imageUrl()
    return html`${image ? html`<img class="image" part=${this.partName("image")} src=${image} alt="" />` : nothing}${
        icon
          ? html`<span class="icon" part=${this.partName("icon")}
              ><slot name=${this.slotName("icon")} @slotchange=${this.onSlotChange}
                >${this.icons.template(this.icon)}</slot
              ></span
            >`
          : html`<slot name=${this.slotName("icon")} @slotchange=${this.onSlotChange}></slot>`
      }<slot @slotchange=${this.onSlotChange}></slot>${
        this.detail ? html`<span class="detail" part=${this.partName("detail")}>${this.detail}</span>` : nothing
      }${
        this.removable
          ? html`<button
              type="button"
              class="delete icon"
              part=${this.partName("delete")}
              aria-label=${this.t("remove")}
              ?disabled=${this.disabled}
              @click=${this.onDelete}
            >
              ${this.icons.template(DELETE_ICON)}
            </button>`
          : nothing
      }`
  }

  ////////////////
  // ## Content detection
  ////////////////

  /**
   * `image="<url>"`:  the URL, or `undefined` for a plain image label (bare `image`), which styles a slotted
   * `<img>` instead.
   */
  private imageUrl(): string | undefined {
    return this.image?.trim() || undefined
  }

  private hasIcon(): boolean {
    return !!this.icon || this.slotted("icon").length > 0
  }

  /** Default-slot text or elements (a slotted `<img>` of an image label doesn't count). */
  private hasText(): boolean {
    // SSR:  the DOM shim has no `childNodes`
    for (const node of this.childNodes ?? []) {
      if (node.nodeType === Node.TEXT_NODE && node.textContent?.trim()) return true
      if (node instanceof Element && !node.slot && node.localName !== "img") return true
    }
    return false
  }

  /** A slot's assignment changed:  icon / text presence may have too. */
  private readonly onSlotChange = () => this.requestUpdate()

  ////////////////
  // ## Behaviour
  ////////////////

  /** Delete button:  cancelable `ui-remove`;  the host removes (or keeps) the label. */
  private readonly onDelete = (event: MouseEvent) => {
    const detail: LabelRemoveDetail = { originalEvent: event }
    this.emit("ui-remove", detail, { cancelable: true })
  }
}

/** `ClassBuilder` extra for an icon-only label -- grammar, not vocabulary. */
const ICON_CLASS = "icon"

/** Glyph of the delete button. */
const DELETE_ICON = "xmark"

/**
 * `ClassBuilder` extra for an image label.
 * - The vocabulary's `image` is a string attribute (it may carry a URL), and `ClassBuilder` emits no class for
 *   the string kind, so the word is added here.
 */
const IMAGE_CLASS = "image"

// packages/ui/src/components/ui-label/UILabel.tsx
import { Show, createMemo } from "solid-js"
import { Dynamic, type JSX } from "@solidjs/web"

import { HostAttribute, IconGlyph, PartContext, proto, SlotContent, UIElement } from "$/ui/core"

import { labelVocabulary } from "./ui-label.vocabulary.en"
import { LabelFallback } from "./ui-label.fallback"

import labelCSS from "./ui-label.css?inline"
import partsCSS from "$/ui/components/ui-parts/ui-parts.css?inline"

/****************
 * ### `<ui-label>`
 * A label:  `<span class="ui … label" part="label">` (`<a>` with `href`) holding, in order, the `image` `<img>`,
 * the icon box, the default slot, the `detail` shorthand and the `removable` delete button.
 * - `icon` class (after the noun) when there's an icon and no text:  the icon centres.
 * - `image`:  a string attribute.  Present (bare / `""`) => class `image` around a slotted `<img>`;  a non-empty
 *   value is the `src` of the label's own `<img class="image" part="image" alt="">`.  `ClassBuilder` emits
 *   nothing for a string kind, so the `image` class goes in as an extra.
 * - `removable`:  a real `<button class="delete icon">` named by the `remove` text;  a click dispatches the
 *   cancelable `ui-remove` -- the label never removes itself, the page does.
 * - Inside a statistic (an owner of `label`, `PartContext`) it is that statistic's `.label` PART:  it renders
 *   `<div class="label" part="label">`, adopts `ui-parts.css` after `ui-label.css` and sets `:state(in-statistic)`.
 * - Host `aria-label` is forwarded to the root, so an icon-only or corner label has a name.
 ****************/
export class UILabel extends UIElement<typeof labelVocabulary> {
  @proto static vocabulary = labelVocabulary
  @proto static styles = { label: labelCSS, parts: partsCSS }
  @proto static Fallback = LabelFallback

  /** Owner, when it's a statistic's label. */
  readonly context = new PartContext(this.host, this.vocabulary.noun)

  /** Light-DOM slot occupancy. */
  readonly slots = new SlotContent(this.host)

  /** Glyph of the `icon` shorthand. */
  readonly glyph = new IconGlyph(() => this.attrs.icon)

  /** Glyph of the delete button. */
  readonly deleteGlyph = new IconGlyph(() => (this.attrs.removable ? DELETE_ICON : undefined))

  /** Host `aria-label`, forwarded to the root. */
  readonly ariaLabel = new HostAttribute(this.host, ARIA_LABEL)

  ////////////////
  // ## Derived state
  ////////////////

  /** Has an icon (shorthand or `icon` slot)? */
  readonly hasIcon = createMemo(() => !!this.attrs.icon || this.slots.has(this.slot("icon")))

  /** Has text (default slot or `detail`)? */
  readonly hasText = createMemo(() => this.slots.has("") || !!this.attrs.detail)

  /** `image` attribute as a URL, or `undefined` when bare (a slotted `<img>`) or absent. */
  readonly imageSrc = createMemo(() => this.attrs.image?.trim() || undefined)

  isDisabled(): boolean {
    return this.attrs.disabled
  }

  protected extraClasses(): string | undefined {
    const extra = [this.attrs.image === undefined ? "" : IMAGE, this.hasIcon() && !this.hasText() ? ICON : ""]
    return extra.filter(Boolean).join(" ") || undefined
  }

  protected hostStates() {
    return { active: this.attrs.active, disabled: this.attrs.disabled }
  }

  /** `ui-parts.css` only while a statistic owns it. */
  protected sheetNames(): string[] {
    return this.context.ownerNoun() ? ["label", "parts"] : ["label"]
  }

  ////////////////
  // ## Rendering
  ////////////////

  render(): JSX.Element {
    return (
      <Show when={this.context.ownerNoun()} fallback={this.label()}>
        <div class={this.vocabulary.noun} part={this.part("label")}>
          <slot />
        </div>
      </Show>
    )
  }

  /** The standalone label box. */
  private label(): JSX.Element {
    return (
      <Dynamic
        component={this.attrs.href ? "a" : "span"}
        class={this.classes()}
        part={this.part("label")}
        href={this.attrs.disabled ? undefined : this.attrs.href}
        target={this.attrs.href ? this.attrs.target : undefined}
        aria-label={this.ariaLabel.get() ?? undefined}
        aria-disabled={this.attrs.disabled && this.attrs.href ? "true" : undefined}
        role={this.ariaLabel.get() && !this.attrs.href ? IMG : undefined}
      >
        <Show when={this.imageSrc()}>
          <img class={IMAGE} part={this.part("image")} src={this.imageSrc()} alt="" />
        </Show>
        <Show when={this.hasIcon()}>
          <span class={ICON} part={this.part("icon")}>
            <slot name={this.slot("icon")}>{this.glyph.svg()}</slot>
          </span>
        </Show>
        <slot />
        <Show when={this.attrs.detail}>
          <span class={DETAIL} part={this.part("detail")}>
            {this.attrs.detail}
          </span>
        </Show>
        <Show when={this.attrs.removable}>
          <button
            type="button"
            class={DELETE_CLASS}
            part={this.part("delete")}
            aria-label={this.text("remove")}
            disabled={this.attrs.disabled}
            onClick={this.onRemove}
          >
            {this.deleteGlyph.svg()}
          </button>
        </Show>
      </Dynamic>
    )
  }

  ////////////////
  // ## Behaviour
  ////////////////

  /** Delete button:  announce;  the page removes the label (or cancels). */
  private readonly onRemove = (event: MouseEvent) => {
    event.preventDefault()
    event.stopPropagation()
    this.emit("ui-remove", { originalEvent: event })
  }
}

/** Grammar words the element adds itself:  the icon box / icon-only class. */
const ICON = "icon"

/** Class of the `image` `<img>`, and the label's extra class for an image label. */
const IMAGE = "image"

/** Class of the `detail` shorthand box. */
const DETAIL = "detail"

/** Classes of the delete button. */
const DELETE_CLASS = "delete icon"

/** Glyph of the delete button (Fomantic's `delete icon`). */
const DELETE_ICON = "xmark"

/** Host attribute forwarded to the root. */
const ARIA_LABEL = "aria-label"

/** Role of a named, non-link label (an icon-only label is a picture of its name). */
const IMG = "img"
