// packages/ui/spike/lit/src/components/divider/UIDivider.ts
import { html, nothing } from "lit"
import { ifDefined } from "lit/directives/if-defined.js"

import { proto, IconRenderer, UIElement } from "../../core"
import { dividerVocabulary } from "$/components/divider/divider.vocabulary.en"
import { DividerFallback } from "$/components/divider/divider.fallback"

import dividerCSS from "$/components/divider/divider.css?inline"

/****************
 * ### `<ui-divider>`
 * A rule, optionally with text:  `<div class="ui ... divider" role="separator" part="divider">`, then an
 * `icon` shorthand's `span.icon` and the text slot.
 * - `role="separator"` rather than `<hr>`:  a horizontal / vertical divider carries text, which `<hr>` can't.
 * - `vertical` adds `aria-orientation="vertical"`;  a `hidden` divider is spacing only, `role="none"`.
 * - `hidden` is property `dividerHidden`:  `hidden` is the host's own boolean.  The ATTRIBUTE keeps its name;
 *   `divider.css`'s `:host([hidden]) { display: contents }` overrides the UA's `display: none`.
 ****************/
export class UIDivider extends UIElement.for(dividerVocabulary) {
  @proto static sheets = [[dividerVocabulary.noun, dividerCSS]] as const
  @proto static Fallback = DividerFallback

  /** icon templates */
  private readonly icons = new IconRenderer(this)

  protected override render() {
    const icon = this.icon
      ? html`<span class="icon" part=${this.partName("icon")}>${this.icons.template(this.icon)}</span>`
      : nothing
    return html`<div
      class=${this.classes()}
      role=${this.dividerHidden ? "none" : "separator"}
      aria-orientation=${ifDefined(this.vertical && !this.dividerHidden ? "vertical" : undefined)}
      part=${this.partName("divider")}
    >
      ${icon}<slot></slot>
    </div>`
  }
}

// packages/ui/src/components/divider/UIDivider.tsx
import { Show } from "solid-js"
import type { JSX } from "@solidjs/web"

import { IconGlyph, proto, UIElement } from "$/ui/core"

import { dividerVocabulary } from "./divider.vocabulary.en"
import { DividerFallback } from "./divider.fallback"

import dividerCSS from "./divider.css?inline"

/****************
 * ### `<ui-divider>`
 * A divider:  `<div class="ui … divider" role="separator" part="divider">` holding the `icon` shorthand's box,
 * then the default slot for text.
 * - `role="separator"`, not `<hr>`:  a horizontal / vertical divider carries text, which `<hr>` can't hold;
 *   `aria-orientation="vertical"` for `vertical`;  a `hidden` divider is `role="none"` (spacing only).
 * - `hidden` is property `dividerHidden` (the vocabulary's `property`):  `hidden` is the host's own boolean.  The
 *   ATTRIBUTE keeps its name;  `divider.css`'s `:host([hidden]) { display: contents }` overrides the UA's
 *   `display: none`, so a hidden divider keeps its spacing.
 ****************/
export class UIDivider extends UIElement<typeof dividerVocabulary> {
  @proto static vocabulary = dividerVocabulary
  @proto static styles = { divider: dividerCSS }
  @proto static Fallback = DividerFallback

  /** Glyph of the `icon` shorthand. */
  readonly glyph = new IconGlyph(() => this.attrs.icon)

  render(): JSX.Element {
    return (
      <div
        class={this.classes()}
        role={this.attrs.hidden ? NONE : SEPARATOR}
        aria-orientation={this.attrs.vertical && !this.attrs.hidden ? VERTICAL : undefined}
        part={this.part("divider")}
      >
        <Show when={this.attrs.icon}>
          <span class={ICON} part={this.part("icon")}>
            {this.glyph.svg()}
          </span>
        </Show>
        <slot />
      </div>
    )
  }
}

/** Role of a divider with a line. */
const SEPARATOR = "separator"

/** Role of a spacing-only divider. */
const NONE = "none"

/** `aria-orientation` of a vertical divider. */
const VERTICAL = "vertical"

/** Class of the icon box. */
const ICON = "icon"
