// packages/ui/src/elements/UIElement.tsx
import {
  Show,
  createContext,
  createEffect,
  createMemo,
  createSignal,
  getOwner,
  untrack,
  useContext,
  type Accessor
} from "solid-js"
import { isServer, type JSX } from "@solidjs/web"
import { customElement, onConnect, onDisconnect, onFormDisabled } from "@spell/solid-element"

import { proto } from "$/util"
import { RUNTIME_KEY, UI, type RuntimeGlobal } from "$/runtime"
import type { ComponentVocabulary, Dictionary } from "$/vocabulary"

import {
  ERROR_EVENT,
  type ClassInput,
  type NativeFallbackHandle,
  type NativeFallbackRoot,
  type AttributeName,
  type AttributeValues,
  type CamelCase,
  type EventName,
  type PartName,
  type SlotName,
  type StateName,
  type TextKey
} from "./elements.types"
import { Cell } from "./Cell"
import { Controlled } from "./Controlled"
import { ElementDefinition } from "./ElementDefinition"
import { PartContext } from "./PartContext"
import { UIHost } from "./UIHost"

/**
 * Base CONTROLLER of every component:  one instance per element, created by the render function the fork
 * (`@spell/solid-element`) calls, holding the component's signals, memos and handlers as fields and methods.
 * - Why a class around a render function:  the library's unit is a function `(props, { element }) => JSX`;
 *   a class keeps the repo's conventions (`@proto static` defaults, methods over loose helpers, one exported
 *   class per file) and gives `this.attrs` / `this.emit()` / `this.classes()` to every component.
 * - `attrs`:  the fork's props -- converted, canonical attribute values, one signal each.
 * - `classes()`:  `ClassBuilder.build()` in a memo, over `classValue()` (overridable, e.g. for controlled state).
 * - Styles:  `await UI.load()`, then the class's sheets (`@proto static styles`) are registered once and adopted
 *   into the shadow root;  content renders only then (`loaded()`), so there's no unstyled flash.
 * - Lifecycle:  `keepAlive` -- the controller lives from first connect to `host.dispose()`, across moves;
 *   `connected()` follows the host.  The constructor may create signals / memos / effects for its OWN fields;
 *   effects that call overridable methods are created in `mount()`, after every subclass field exists.
 * - Errors:  the fork's boundary catches anything thrown while constructing, rendering or updating;  `failed()`
 *   logs and dispatches `ui-error`, then the family's `Fallback` (a native `<button>`, `<select>` ...) replaces
 *   the shadow content -- see `renderFallback()`.
 * - NOTE: Solid 2 forbids signal writes inside an owned scope (component body, memo, effect compute).  Write
 *   from event handlers, promise callbacks or the fork's hooks (deferred, see `connected`).
 */
export abstract class UIElement<V extends ComponentVocabulary = ComponentVocabulary> {
  declare vocabulary: V
  declare styles: Readonly<Record<string, string>>
  declare Host: typeof UIHost
  declare isPart: boolean
  declare delegatesFocus: boolean
  declare slotAssignment: SlotAssignmentMode
  declare formAssociated: boolean
  declare Fallback: FallbackClass | undefined

  /** Sheets to adopt after the foundation, by registry name => CSS text, in order. */
  @proto static styles: Readonly<Record<string, string>> = {}

  /** Host base class;  `FormElement` swaps in `FormHost` (the form-control API). */
  @proto static Host = UIHost

  /** A generic content part:  transparent to other parts' owner lookups (`PartContext`).  `ContentPart` sets it. */
  @proto static isPart = false

  /** Shadow root `delegatesFocus`;  an element with nothing focusable inside (`<ui-item>`) turns it off. */
  @proto static delegatesFocus = true

  /**
   * Shadow root `slotAssignment`:  `manual` lets an element hand CHOSEN children to chosen `<slot>`s
   * (`slot.assign()`), e.g. `<ui-accordion>` wrapping each title + content pair in its own `<details>`.
   * - NOTE: a `manual` root assigns nothing by itself:  every `<slot>` it renders stays empty until assigned.
   */
  @proto static slotAssignment: SlotAssignmentMode = "named"

  /** Form-associated (the fork's `formAssociated` option):  `FormElement`, and `UIButton` for submit / reset. */
  @proto static formAssociated = false

  /** Native fallback shown when this element fails (`$/components/<name>/<name>.fallback.ts`);  none => a `<slot>`. */
  @proto static Fallback: FallbackClass | undefined = undefined

  /**
   * Wrap each element's render in the fork's error boundary (`errorBoundary`), so one element's error disables
   * THAT element instead of halting reactivity for the page.  Read at `define()`;  a switch only so `docs/report.md`
   * can measure the cost.
   */
  static isolateErrors = true

  /**
   * A value the host APP may provide around any `ui-*` element (`<AppContext value={...}>`);  read by every
   * controller as `app`.
   * - Proves owner adoption across the custom-element boundary (the Solid host page's identity probe,
   *   `tools/frameworks/solid/identity.js`).
   * - `null` default:  Solid 2's `useContext` throws on a context with neither a default nor a provider.
   */
  static readonly AppContext = createContext<unknown>(null)

  /** Definition per registered tag, canonical and translated. */
  static readonly definitions = new Map<string, ElementDefinition>()

  /** The element. */
  readonly host: UIHost

  /** Names and converters for this tag. */
  readonly definition: ElementDefinition

  /** Converted canonical attribute values (the fork's props);  reading one tracks it. */
  readonly attrs: AttributeValues<V>

  /** What the app provides as `UIElement.AppContext` above this element, else `null`. */
  readonly app: unknown

  /** Fomantic class string of the component's root. */
  readonly classes: Accessor<string>

  /** Runtime loaded and sheets adopted. */
  readonly loaded: Accessor<boolean>

  /**
   * In the document?  Tracked;  follows connects / disconnects one microtask late.
   * - Deferred:  the fork's hooks run inside `connectedCallback`, which may run inside a Solid render (an app
   *   inserting the element), where a signal write would throw.
   */
  readonly connected: Cell<boolean>

  /** Disabled by an ancestor `<fieldset disabled>` (form-associated elements only, the fork's hook);  tracked. */
  readonly formDisabled = new Cell(false)

  /** Sets `loaded`. */
  private readonly setLoaded: (value: boolean) => void

  constructor(host: UIHost, definition: ElementDefinition, attrs: AttributeValues<V>) {
    this.host = host
    this.definition = definition
    this.attrs = attrs
    host.controller = this
    this.app = useContext(UIElement.AppContext)
    this.connected = new Cell(isServer || host.isConnected)
    const classInput = this.classInput()
    // `lazy`:  memos compute EAGERLY in Solid 2, and this one calls overridable methods that read subclass
    // fields, which don't exist yet while this constructor runs
    this.classes = createMemo(() => definition.builder.build(classInput, { extra: this.extraClasses() }), {
      lazy: true
    })
    // on the server (the SSR probe) there are no sheets to adopt:  render at once
    const loaded = isServer || (RUNTIME_KEY in globalThis && !!(globalThis as RuntimeGlobal)[RUNTIME_KEY])
    const [isLoaded, setLoaded] = createSignal(loaded)
    this.loaded = isLoaded
    this.setLoaded = setLoaded
    if (isServer) return
    const root = host.renderRoot
    const onSlotChange = (event: Event) => PartContext.slotChanged(event.target as HTMLSlotElement)
    root.addEventListener("slotchange", onSlotChange)
    host.addReleaseCallback(() => root.removeEventListener("slotchange", onSlotChange))
    const sync = () => queueMicrotask(() => this.connected.set(host.isConnected))
    onConnect(sync)
    onDisconnect(sync)
    // the fork replays the last state to a late registration -- i.e. right here, inside the component body,
    // where Solid 2 forbids the write:  defer it then;  platform calls (no owner) write at once
    if (this.formAssociated) {
      onFormDisabled((disabled) => {
        if (getOwner()) queueMicrotask(() => this.formDisabled.set(disabled))
        else this.formDisabled.set(disabled)
      })
    }
    if (!loaded) void UI.load().then(() => this.onLoaded())
  }

  ////////////////
  // ## Rendering
  ////////////////

  /** The component's shadow content;  runs once, after styles are adopted. */
  abstract render(): JSX.Element

  /**
   * Create the effects that call overridable methods, then return the content.  Called by the render function.
   * - Host states follow `hostStates()`;  `ready` resolves once content has rendered with styles.
   */
  mount(): JSX.Element {
    // adopted HERE when the runtime was already loaded:  `sheetNames()` is overridable and may read subclass
    // fields, which don't exist yet while the base constructor runs
    if (!isServer && untrack(this.loaded)) this.adoptStyles()
    createEffect(
      () => this.hostStates(),
      (states) => {
        for (const [name, on] of Object.entries(states)) this.host.setState(name, !!on)
      }
    )
    createEffect(
      () => this.loaded(),
      (loaded) => {
        if (loaded) queueMicrotask(() => this.host.markReady())
      }
    )
    // the APPLY uses the computed names:  calling `sheetNames()` there again would read its signals untracked
    createEffect(
      () => this.sheetNames().join(SHEET_SEPARATOR),
      (names) => {
        if (untrack(this.loaded)) UI.styles.adoptInto(this.host.renderRoot, names ? names.split(SHEET_SEPARATOR) : [])
      },
      { defer: true }
    )
    return <Show when={this.loaded()}>{this.render()}</Show>
  }

  /**
   * Registry names of the sheets to adopt now, in order;  default every `styles` entry.
   * - Tracked:  an element whose sheets depend on context (a label owned by a statistic adds `parts.css`)
   *   overrides it, and the root re-adopts when it changes.
   */
  protected sheetNames(): string[] {
    return Object.keys(this.styles)
  }

  /** Extra classes after the noun, e.g. `icon` for an icon-only button. */
  protected extraClasses(): string | undefined {
    return undefined
  }

  /** Value `ClassBuilder` sees for canonical attribute `name`;  default the converted attribute. */
  protected classValue(name: AttributeName<V>): unknown {
    return this.attrs[this.definition.attribute(name).key as keyof AttributeValues<V>]
  }

  /**
   * Classes for a SECOND root from chosen attribute values, e.g. the wrapper of a labeled button.
   * - Keys are canonical attribute names, type-checked against the vocabulary.
   */
  protected buildClasses(values: Partial<Record<AttributeName<V>, unknown>>, extra?: string): string {
    return this.definition.builder.build(values, { extra })
  }

  /** Custom states to set on the host;  default none. */
  protected hostStates(): Partial<Record<StateName<V>, boolean>> {
    return {}
  }

  /** True when the element can't be used;  the host swallows clicks then. */
  isDisabled(): boolean {
    return false
  }

  /**
   * Auto-controlled state for attribute `name` (see `Controlled`):  the host's property when set, else internal.
   * - MUST be called from a field initializer or constructor (it creates a signal).
   */
  protected controlled<N extends AttributeName<V>>(
    name: N,
    initial: AttributeValues<V>[CamelCase<N> & keyof AttributeValues<V>]
  ): Controlled<AttributeValues<V>[CamelCase<N> & keyof AttributeValues<V>]> {
    const { key, property } = this.definition.attribute(name)
    type Value = AttributeValues<V>[CamelCase<N> & keyof AttributeValues<V>]
    return new Controlled<Value>({
      host: this.host,
      key,
      property,
      value: () => this.attrs[key as keyof AttributeValues<V>] as Value | undefined,
      initial
    })
  }

  /** `ClassBuilder` input:  getters over `classValue()`, so the classes memo tracks exactly what it reads. */
  private classInput(): ClassInput {
    const input: Record<string, unknown> = {}
    for (const { spec } of this.definition.attributes) {
      Object.defineProperty(input, spec.name, {
        get: () => this.classValue(spec.name as AttributeName<V>),
        enumerable: true
      })
    }
    return input
  }

  ////////////////
  // ## Names
  ////////////////

  /** `part` attribute for canonical part `name`. */
  part(name: PartName<V>): string {
    return this.definition.part(name)
  }

  /** Localized slot name for canonical `name`. */
  slot(name: SlotName<V>): string {
    return this.definition.slot(name)
  }

  /**
   * Text for `key` in the current locale, via `UI.i18n`, scoped to this component's canonical tag.
   * - Another family's text under the same key never leaks in (see `registerTexts()`).
   */
  text(key: TextKey<V>, params?: Record<string, string | number>): string {
    return UI.i18n.t(key, params, this.vocabulary.tag)
  }

  ////////////////
  // ## Events
  ////////////////

  /**
   * Dispatch vocabulary event `name` from the host:  `bubbles`, `composed`, `cancelable` as the vocabulary says.
   * - Returns false when a cancelable event was vetoed (`preventDefault()`).
   */
  emit(name: EventName<V>, detail: object): boolean {
    const spec = this.definition.vocabulary.events.find((event) => event.name === name)
    const event = new CustomEvent(this.definition.event(name), {
      bubbles: true,
      composed: true,
      cancelable: !!spec?.cancelable,
      detail
    })
    return this.host.dispatchEvent(event)
  }

  ////////////////
  // ## Styles
  ////////////////

  /** Runtime arrived:  adopt, show content. */
  private onLoaded() {
    this.adoptStyles()
    this.setLoaded(true)
  }

  /** Register this class's sheets once, then adopt foundation + sheets into the shadow root. */
  private adoptStyles() {
    if (!SHEETS.has(this.styles)) {
      SHEETS.add(this.styles)
      for (const [name, css] of Object.entries(this.styles)) if (!UI.styles.has(name)) UI.styles.register(name, css)
    }
    UI.styles.adoptInto(
      this.host.renderRoot,
      untrack(() => this.sheetNames())
    )
  }

  ////////////////
  // ## Definition
  ////////////////

  /**
   * Define this component under its vocabulary's tag, or under a translated alias:
   * `UIButton.define("ie-boton", es)` registers `<ie-boton primario color="rojo">` with localized
   * attribute / property / event names mapping onto the same controller.
   * - Everything platform-shaped is a fork option:  base class, `delegatesFocus`, internals, form association,
   *   `keepAlive`, the error boundary and its `onError` / `fallback`.
   * - Idempotent per tag;  returns the element class.
   */
  static define(this: UIElementClass, tag?: string, dictionary?: Dictionary): CustomElementConstructor {
    const definition = new ElementDefinition(this.prototype.vocabulary, { tag, dictionary })
    return customElements.get(definition.tag) ?? UIElement.defineTag.call(this, definition)
  }

  /**
   * `define()` minus the idempotence check:  record `definition`, then hand the fork its tag, props, component
   * and options.
   * - For a tag already defined, the fork swaps the component in place (Vite dev only:  hot module replacement
   *   re-defines a new version of a class through here, see `HotDefinitions`).
   */
  static defineTag(this: UIElementClass, definition: ElementDefinition): CustomElementConstructor {
    const { vocabulary, Host, isPart, delegatesFocus, slotAssignment, formAssociated, Fallback } = this.prototype
    UIElement.definitions.set(definition.tag, definition)
    PartContext.define(vocabulary, definition.tag, isPart, "ownsPart" in this.prototype)
    UIElement.registerTexts(vocabulary)
    return customElement(
      definition.tag,
      definition.props,
      (attrs, { element }) => new this(element as unknown as UIHost, definition, attrs).mount(),
      {
        BaseElement: Host,
        shadowRootInit: { mode: "open", delegatesFocus, slotAssignment },
        internals: true,
        formAssociated,
        keepAlive: true,
        errorBoundary: UIElement.isolateErrors,
        onError: (element, error) => UIElement.failed(element as unknown as UIHost, error),
        fallback: (element, error) => UIElement.renderFallback(element as unknown as UIHost, error, Fallback)
      }
    )
  }

  ////////////////
  // ## Errors
  ////////////////

  /**
   * The fork's `onError`:  an error escaped this element's render, construction or an effect.
   * - SIDE EFFECT:  one `console.error` naming the tag;  a cancelable, composed `ui-error` (`{ error }`) -- an
   *   app cancelling it keeps the fallback out;  resolves `host.ready`;  drops the (broken) controller.
   * - Runs outside any owner (the fork's rule), so it may write signals.
   */
  private static failed(host: UIHost, error: unknown) {
    console.error(`<${host.localName}> failed:`, error)
    host.controller = undefined
    host.markReady()
    const event = new CustomEvent(ERROR_EVENT, { bubbles: true, composed: true, cancelable: true, detail: { error } })
    if (!host.dispatchEvent(event)) CANCELLED.add(host)
  }

  /**
   * The fork's `fallback`:  `Fallback.render(host, renderRoot, error, internals)` -- plain DOM, library-neutral
   * markup -- or a bare `<slot>` for an element without one (a group keeps its children visible).
   * - Built a microtask LATER, into the render root directly:  the boundary's own insert would otherwise clear
   *   the root after us, and a fallback like the dropdown's must be attached to set its validity anchor.
   * - Skipped when an app cancelled `ui-error`;  its handle is disposed with the element.
   */
  private static renderFallback(host: UIHost, error: unknown, Fallback: FallbackClass | undefined): undefined {
    if (CANCELLED.has(host)) return undefined
    queueMicrotask(() => {
      const root = host.renderRoot
      const handle = Fallback
        ? Fallback.render(host, root, error, host.internals)
        : (root.replaceChildren(host.ownerDocument.createElement("slot")), undefined)
      if (handle) host.addReleaseCallback(() => handle.dispose())
    })
    return undefined
  }

  /**
   * Register `vocabulary` with `UI.vocabulary` and its English texts with `UI.i18n` when the class is DEFINED,
   * not on first connect, so `UI.i18n.t()` and translations see them before any instance exists.
   * - Texts are English DEFAULTS scoped to the canonical tag (`I18n.registerDefaults()`):  any registered string
   *   (an app's English, a translation) beats them, and two families may share a key (`label`) with different
   *   text.  Code outside the element (`UI.i18n.t("notifications")`, unscoped) gets the FIRST family's.
   * - Loads the runtime if it isn't yet;  idempotent per vocabulary.
   */
  private static registerTexts(vocabulary: ComponentVocabulary) {
    if (isServer || TEXTS.has(vocabulary)) return
    TEXTS.add(vocabulary)
    if ((globalThis as RuntimeGlobal)[RUNTIME_KEY]) register()
    else void UI.load().then(register)

    /** Hand the vocabulary and its English texts to the runtime. */
    function register() {
      UI.vocabulary.register(vocabulary)
      const texts: Record<string, string> = {}
      for (const { key, text } of vocabulary.texts) texts[key] = text
      UI.i18n.registerDefaults(texts, vocabulary.tag)
    }
  }
}

/** A concrete `UIElement` subclass, as `define()` sees it. */
export type UIElementClass = {
  new (host: UIHost, definition: ElementDefinition, attrs: any): UIElement<any>
  prototype: UIElement<any>
}

/** A per-family native fallback class (`ButtonFallback` ...), as `NativeFallback.render()` is called. */
export type FallbackClass = {
  render(
    host: HTMLElement,
    root: NativeFallbackRoot,
    error?: unknown,
    internals?: ElementInternals
  ): NativeFallbackHandle
}

/** Joins sheet registry names into one comparable value (names never contain it). */
const SHEET_SEPARATOR = " "

/** `styles` maps whose sheets are registered with the runtime. */
const SHEETS = new WeakSet<object>()

/** Vocabularies whose texts are registered (or queued) with the runtime. */
const TEXTS = new WeakSet<ComponentVocabulary>()

/** Hosts whose `ui-error` an app cancelled:  no fallback. */
const CANCELLED = new WeakSet<UIHost>()

// packages/ui/spike/lit/src/elements/UIElement.ts
import { LitElement, type PropertyValues } from "lit"

import { proto } from "$/util"
import { ClassBuilder } from "$/elements"
import { loadUI, RUNTIME_KEY, type RuntimeGlobal, type UIRuntime } from "$/runtime"
import { type ComponentVocabulary, type Dictionary, type LocalizedVocabulary, Vocabulary } from "$/vocabulary"

import {
  ERROR_EVENT,
  ERRORED_STATE,
  type DeclaredProps,
  type EmitOptions,
  type EventName,
  type FallbackClass,
  type PartName,
  type SheetEntry,
  type SlotName,
  type TextKey
} from "./elements.types"
import { PartOwners } from "./PartOwners"
import { VocabularyProperties, type VocabularyDeclaration } from "./VocabularyProperties"

/**
 * Lit base class for every `ui-*` element in the spike.
 * - Attributes come FROM THE VOCABULARY:  `class UIButton extends UIElement.for(buttonVocabulary)` declares one
 *   reactive property per vocabulary attribute (see `VocabularyProperties`) and types them all
 *   (`VocabularyProps`), so no component spells an attribute name.
 * - Shadow root via `createRenderRoot()`, `delegatesFocus` from `@proto static delegatesFocus`.
 * - Styles:  NOT Lit's `static styles`.  The shared `UI` runtime owns every sheet (`UI.styles`), so on connect
 *   the element awaits `UI.load()` and adopts foundation + `@proto static sheets` + utilities + app sheet.
 *   The FIRST render waits for the runtime too (`scheduleUpdate()`), so nothing paints unstyled.
 * - `attachInternals()` always:  custom states (`setState()`), ARIA, and `internals.form` for form-associated
 *   subclasses.
 * - Helpers read names through the vocabulary:  `emit("ui-change")` dispatches the LOCALIZED event on a
 *   translated element, `partName("icon")` adds the localized part, `slotName("icon")` is the localized slot.
 * - Controlled properties (`transition()`):  event first, then the change -- unless the event was cancelled
 *   or the host wrote the property from inside its handler, which wins (React-style revert).
 * - Upgrade backstop:  Lit's own `__saveInstanceProperties()` already deletes and replays properties a
 *   framework set before the element was defined, for every declared property.  Nothing to add.
 * - Registration (`define()`) also records the tag with `PartOwners` (owner context) and queues the
 *   vocabulary's `texts` for `UI.i18n`, registered once the runtime is in.
 * - Every `slotchange` in the shadow root is reported to `PartOwners`, so re-slotted parts find their owner.
 * - Failure:  a throw anywhere in an update (`willUpdate()`, `render()`, `updated()` ...) is caught;  the element
 *   logs it once, dispatches a cancelable `ui-error`, gets `:state(errored)`, shows its family's native fallback
 *   (`@proto static Fallback`) and never renders again -- see `failed()`.
 */
export class UIElement extends LitElement {
  /** canonical vocabulary;  installed on the prototype by `for()` */
  declare vocabulary: ComponentVocabulary
  /** localized names when registered under a translated tag by `define(tag, dictionary)` */
  declare localized: LocalizedVocabulary | undefined
  /** vocabulary property declarations, by property name;  installed by `declareVocabulary()` */
  declare declarations: ReadonlyMap<string, VocabularyDeclaration>
  /** shadow root delegates focus to its first focusable element (buttons, comboboxes) */
  declare delegatesFocus: boolean
  /** sheets to register and adopt, in cascade order after the foundation */
  declare sheets: readonly SheetEntry[]
  /** a generic content part (`ContentPart`):  transparent to other parts' owner lookup */
  declare contentPart: boolean
  /** forward the host's `aria-label` into the shadow root (see `ariaLabelled`), e.g. icon-only buttons */
  declare forwardsAriaLabel: boolean
  /**
   * Native fallback shown when an update throws (`$/components/<name>/<name>.fallback.ts`);  none => a bare
   * `<slot>`, so a group's children stay visible.
   * - NOTE: capitalized (a class), so it can never clash with a vocabulary attribute's property.
   */
  declare Fallback: FallbackClass | undefined

  @proto static localized: LocalizedVocabulary | undefined = undefined
  @proto static delegatesFocus = false
  @proto static sheets: readonly SheetEntry[] = []
  @proto static contentPart = false
  @proto static forwardsAriaLabel = false
  @proto static Fallback: FallbackClass | undefined = undefined

  /** `ElementInternals`:  states, ARIA, forms */
  readonly internals: ElementInternals

  /** properties being transitioned right now => did the host write them during the event? */
  private readonly hostWrites = new Map<PropertyKey, boolean>()

  /** Set by the first failed update (`failed()`):  the element never renders again. */
  private failure: { error: unknown } | undefined

  constructor() {
    super()
    this.internals = this.attachInternals()
    for (const [name, declaration] of this.declarations ?? []) {
      if (declaration.initial !== undefined) (this as Record<string, unknown>)[name] = declaration.initial
    }
  }

  ////////////////
  // ## Declaration
  ////////////////

  /**
   * `this` extended with one reactive property per attribute of `vocabulary`, typed by kind.
   * - `Overrides` retypes properties the vocabulary can't describe, e.g. `{ value: DropdownValue }`.
   * - Returns an intermediate class;  `class UIButton extends UIElement.for(buttonVocabulary) {}`.
   */
  static for<T extends typeof UIElement, V extends ComponentVocabulary, Overrides extends object = object>(
    this: T,
    vocabulary: V
  ): T & (new (...args: any[]) => InstanceType<T> & DeclaredProps<V, Overrides>) {
    const Declared = class extends (this as typeof UIElement) {}
    Object.defineProperty(Declared.prototype, "vocabulary", { value: vocabulary, writable: true, configurable: true })
    Declared.declareVocabulary(vocabulary)
    return Declared as never
  }

  /**
   * `createProperty()` for every attribute of `vocabulary`, under canonical or `localized` names.
   * - SIDE EFFECT:  installs `declarations` on this class's prototype.
   */
  protected static declareVocabulary(vocabulary: ComponentVocabulary, localized?: LocalizedVocabulary) {
    const declarations = VocabularyProperties.declarations(vocabulary, localized)
    for (const [name, declaration] of declarations) this.createProperty(name, declaration)
    Object.defineProperty(this.prototype, "declarations", { value: declarations, writable: true, configurable: true })
  }

  /** Mirror `@proto static delegatesFocus` into Lit's `shadowRootOptions`, which SSR reads. */
  static protoDefined(name: string | symbol, value: unknown) {
    if (name === "delegatesFocus") this.shadowRootOptions = { ...LitElement.shadowRootOptions, delegatesFocus: !!value }
  }

  ////////////////
  // ## Registration
  ////////////////

  /**
   * Register this class under its vocabulary tag, or under a translated `tag` with `dictionary`.
   * - Translated:  defines a SUBCLASS whose properties are redeclared with localized attribute names and
   *   value maps (Lit fixes `attribute:` at declaration time), and whose `emit()` / `partName()` / `slotName()`
   *   use localized names.  Everything inside stays canonical.
   * - The tag's prefix (`ie` of `ie-boton`) is the event prefix (`ie-cambio`).
   * - Idempotent:  returns the already-registered class.
   */
  static define(tag?: string, dictionary?: Dictionary): CustomElementConstructor {
    const vocabulary = this.prototype.vocabulary
    const name = tag ?? vocabulary.tag
    const existing = customElements.get(name)
    if (existing) return existing
    PartOwners.register(name, vocabulary, this.prototype.contentPart)
    UIElement.queueTexts(vocabulary)
    if (!dictionary && name === vocabulary.tag) {
      customElements.define(name, this)
      return this
    }
    const localized = {
      ...new Vocabulary().resolve(vocabulary, name.slice(0, name.indexOf("-")), dictionary),
      tag: name
    }
    const Localized = class extends this {}
    Object.defineProperty(Localized.prototype, "localized", { value: localized, writable: true, configurable: true })
    Localized.declareVocabulary(vocabulary, localized)
    customElements.define(name, Localized)
    void loadUI().then((ui) => {
      ui.vocabulary.register(vocabulary)
      ui.vocabulary.localized.set(name, localized)
    })
    return Localized
  }

  ////////////////
  // ## Lifecycle
  ////////////////

  /**
   * Open shadow root, delegating focus per `delegatesFocus`;  reuses a declarative (SSR) one.
   * - SIDE EFFECT:  reports every `slotchange` inside to `PartOwners` (it bubbles, but isn't composed).
   */
  protected override createRenderRoot() {
    const root = this.shadowRoot ?? this.attachShadow({ mode: "open", delegatesFocus: this.delegatesFocus })
    root.addEventListener("slotchange", UIElement.onSlotChange)
    return root
  }

  /** Also watch the host's `aria-label` when it's forwarded. */
  static override get observedAttributes() {
    const names = super.observedAttributes
    return this.prototype.forwardsAriaLabel ? [...names, ARIA_LABEL] : names
  }

  override attributeChangedCallback(name: string, old: string | null, value: string | null) {
    if (name === ARIA_LABEL && this.forwardsAriaLabel) this.requestUpdate()
    else super.attributeChangedCallback(name, old, value)
  }

  /** Adopt sheets once the runtime is in (at once if it already is). */
  override connectedCallback() {
    super.connectedCallback()
    if (UIElement.runtime) this.adoptSheets()
    else void UIElement.loadRuntime().then(() => this.adoptSheets())
  }

  /**
   * Hold the FIRST render until the runtime has loaded, so it paints styled and can use `UI`.
   * - Every update runs through `guardedUpdate()`, so a throw becomes `failed()`, not an unhandled rejection.
   */
  protected override scheduleUpdate(): void | Promise<unknown> {
    if (UIElement.runtime) return this.guardedUpdate()
    return UIElement.loadRuntime().then(() => this.guardedUpdate())
  }

  /**
   * `super.scheduleUpdate()` (Lit's `performUpdate()`), with any throw handed to `failed()`.
   * - Catches the whole cycle:  `performUpdate()` rethrows from `willUpdate()` / `update()` / `render()` after
   *   marking the update done, and `firstUpdated()` / `updated()` throw straight through.
   */
  private guardedUpdate(): void | Promise<unknown> {
    try {
      return super.scheduleUpdate()
    } catch (error) {
      this.failed(error)
    }
  }

  /** Never again after a failure:  Lit would re-render over the fallback, and `updated()` hooks would fight it. */
  protected override shouldUpdate(changed: PropertyValues): boolean {
    return !this.failure && super.shouldUpdate(changed)
  }

  /**
   * Register this class's sheets (once) and adopt `sheetNames()` into the shadow root.
   * - Call again when `sheetNames()` changes;  a no-op before the runtime is in (connect adopts then).
   */
  protected adoptSheets() {
    const ui = UIElement.runtime
    if (!ui || !this.isConnected) return
    const constructor = this.constructor as typeof UIElement
    if (!UIElement.registered.has(constructor)) {
      for (const [name, css] of this.sheets) ui.styles.register(name, css)
      UIElement.registered.add(constructor)
    }
    ui.styles.adoptInto(this.renderRoot as ShadowRoot, this.sheetNames())
  }

  /**
   * Registered sheet names to adopt, in cascade order:  `sheets` by default.
   * - Override to add another component's sheet by NAME, e.g. a statistic's label adopts `parts`;  a name
   *   nobody registered is skipped by `UI.styles`, and picked up once it is.
   */
  protected sheetNames(): string[] {
    return this.sheets.map(([name]) => name)
  }

  ////////////////
  // ## Failure
  ////////////////

  /**
   * The first update that threw:  degrade to the family's native fallback.
   * - SIDE EFFECT:
   *   - one `console.error` naming the tag, with the cause
   *   - `:state(errored)`
   *   - a cancelable, bubbling, composed `ui-error` (`{ error }`);  an app cancelling it keeps the fallback out
   *     and gets an EMPTY shadow root to take over
   *   - unless cancelled, `Fallback.render(host, shadowRoot, error, internals)` replaces the shadow content
   *     (plain DOM, the same markup the Solid spike renders);  adopted sheets stay, so it's styled
   * - Later updates are skipped (`shouldUpdate()`), so this runs once per instance.
   */
  private failed(error: unknown) {
    if (this.failure) return
    this.failure = { error }
    console.error(`<${this.localName}> failed:`, error)
    this.setState(ERRORED_STATE, true)
    const event = new CustomEvent(ERROR_EVENT, { bubbles: true, composed: true, cancelable: true, detail: { error } })
    const root = this.renderRoot as ShadowRoot
    // cancelled:  the last good render is stale (it never updates again), so it goes too, as in the Solid spike
    if (!this.dispatchEvent(event)) root.replaceChildren()
    else if (this.Fallback) this.Fallback.render(this, root, error, this.internals)
    else root.replaceChildren(this.ownerDocument.createElement("slot"))
  }

  ////////////////
  // ## Runtime
  ////////////////

  /** The page runtime once loaded;  `undefined` before, and always under SSR. */
  static runtime: UIRuntime | undefined = (globalThis as RuntimeGlobal)[RUNTIME_KEY]

  /** In-flight load, shared by every element. */
  private static loading: Promise<UIRuntime> | undefined

  /** Classes whose sheets are registered. */
  private static readonly registered = new WeakSet<typeof UIElement>()

  /** Vocabularies whose `texts` wait for the runtime. */
  private static readonly pendingTexts: ComponentVocabulary[] = []

  /** `UI.load()`, remembering the instance so later callers stay synchronous. */
  static loadRuntime(): Promise<UIRuntime> {
    return (UIElement.loading ??= loadUI().then((ui) => {
      UIElement.runtime = ui
      UIElement.flushTexts(ui)
      return ui
    }))
  }

  /**
   * Register `vocabulary`'s English `texts` with `UI.i18n`:  now if the runtime is in, else once it loads.
   * - Doesn't load the runtime itself, so `define()` stays side-effect-light (and SSR-safe).
   */
  private static queueTexts(vocabulary: ComponentVocabulary) {
    if (!vocabulary.texts.length) return
    UIElement.pendingTexts.push(vocabulary)
    if (UIElement.runtime) UIElement.flushTexts(UIElement.runtime)
  }

  /**
   * Add every pending vocabulary's texts to the `en` pack, so `UI.i18n.t("or")` resolves through the pack
   * and a translation (`register("es", { or: "o" })`) wins over it.
   * - A key the pack already has keeps its text:  shared keys (`loading`) stay the runtime's.
   */
  private static flushTexts(ui: UIRuntime) {
    const pack: Record<string, string> = {}
    for (const vocabulary of UIElement.pendingTexts.splice(0)) {
      for (const { key, text } of vocabulary.texts) if (!ui.i18n.has(key) && !(key in pack)) pack[key] = text
    }
    if (Object.keys(pack).length) ui.i18n.register("en", pack)
  }

  ////////////////
  // ## Classes, states, names
  ////////////////

  /**
   * Fomantic class string for the current properties, via the vocabulary's `ClassBuilder`.
   * - `overrides` replaces values by CANONICAL attribute name, e.g. the labeled-button wrapper's `labeled`.
   */
  protected classes(extra?: string, overrides?: Readonly<Record<string, unknown>>): string {
    const values: Record<string, unknown> = {}
    for (const [name, declaration] of this.declarations) {
      values[declaration.spec.name] = (this as Record<string, unknown>)[name]
    }
    if (overrides) Object.assign(values, overrides)
    return UIElement.builder(this.vocabulary).build(values, { extra })
  }

  /** Turn custom state `name` (`:state(open)`) on or off. */
  protected setState(name: string, on: boolean) {
    const states = this.internals.states as Set<string> | undefined
    if (!states) return
    if (on) states.add(name)
    else states.delete(name)
  }

  /** `part` attribute for canonical part `name`, plus its localized name on a translated element. */
  protected partName(name: PartName<this["vocabulary"]>): string {
    const localized = this.localized?.names.parts.get(name)
    return localized && localized !== name ? `${name} ${localized}` : name
  }

  /** Slot name for canonical slot `name`:  localized on a translated element. */
  protected slotName(name: SlotName<this["vocabulary"]>): string {
    return this.localized?.names.slots.get(name) ?? name
  }

  /**
   * User-visible text `key`:  `UI.i18n` when it knows the key, else the vocabulary's English text.
   * - `{name}` placeholders filled from `params`.  Works before the runtime loads (and under SSR).
   */
  protected t(key: TextKey<this["vocabulary"]>, params?: Record<string, string | number>): string {
    const i18n = UIElement.runtime?.i18n
    if (i18n?.has(key)) return i18n.t(key, params)
    const text = this.vocabulary.texts.find((spec) => spec.key === key)?.text ?? key
    return params ? text.replace(/\{(\w+)\}/g, (match, name: string) => String(params[name] ?? match)) : text
  }

  /**
   * The host's `aria-label`, for elements that forward it (`forwardsAriaLabel`) onto their semantic root:
   * an icon-only button or label has no text to be named by.
   */
  protected ariaLabelled(): string | undefined {
    return this.getAttribute(ARIA_LABEL) ?? undefined
  }

  /** Light-DOM children assigned to canonical slot `name` (`""` ~== default slot). */
  protected slotted(name: SlotName<this["vocabulary"]>): Element[] {
    const slot = this.slotName(name)
    // SSR:  the DOM shim has no light-DOM children, so slotted content is invisible on the server
    return [...(this.children ?? [])].filter((child) => child.slot === slot)
  }

  ////////////////
  // ## Events and controlled properties
  ////////////////

  /**
   * Dispatch canonical event `name` (localized on a translated element):  bubbling, composed.
   * - Returns false when a cancelable event was cancelled.
   */
  protected emit<D>(name: EventName<this["vocabulary"]>, detail: D, { cancelable = false }: EmitOptions = {}): boolean {
    const type = this.localized?.names.events.get(name) ?? name
    return this.dispatchEvent(new CustomEvent(type, { detail, bubbles: true, composed: true, cancelable }))
  }

  /**
   * A user-driven change of controlled `property` to `next`:  event first, then the change.
   * - Skipped when the event was cancelled, or when the host set `property` from its handler -- the host's
   *   value is authoritative, so `el.value = old` in a `ui-change` handler reverts the UI.
   * - Returns true when `next` was applied.
   */
  protected transition<K extends keyof this>(
    property: K,
    next: this[K],
    event: EventName<this["vocabulary"]>,
    detail: object,
    options: EmitOptions = {}
  ): boolean {
    this.hostWrites.set(property, false)
    let allowed = false
    try {
      allowed = this.emit(event, detail, options)
    } finally {
      if (this.hostWrites.get(property)) allowed = false
      this.hostWrites.delete(property)
    }
    if (allowed) this[property] = next
    return allowed
  }

  /** Notice host writes to properties inside `transition()`. */
  override requestUpdate(...args: Parameters<LitElement["requestUpdate"]>) {
    const [name] = args
    if (name !== undefined && this.hostWrites.has(name)) this.hostWrites.set(name, true)
    super.requestUpdate(...args)
  }

  /** Changed CANONICAL attribute names in `changed`, for subclasses that care. */
  protected changedAttributes(changed: PropertyValues): Set<string> {
    const names = new Set<string>()
    for (const key of changed.keys()) {
      const spec = this.declarations.get(String(key))?.spec
      if (spec) names.add(spec.name)
    }
    return names
  }

  ////////////////
  // ## Internals
  ////////////////

  /** `ClassBuilder` per vocabulary, built once. */
  private static builder(vocabulary: ComponentVocabulary): ClassBuilder {
    let builder = UIElement.builders.get(vocabulary)
    if (!builder) UIElement.builders.set(vocabulary, (builder = new ClassBuilder(vocabulary)))
    return builder
  }

  /** Cache for `builder()`. */
  private static readonly builders = new WeakMap<ComponentVocabulary, ClassBuilder>()

  /** Report a slot's new assignment to `PartOwners`;  shared by every shadow root. */
  private static onSlotChange(event: Event) {
    const slot = event.target
    if (slot instanceof HTMLSlotElement) PartOwners.reslotted(slot.assignedElements({ flatten: true }))
  }
}

/** Platform attribute forwarded by `forwardsAriaLabel` elements. */
const ARIA_LABEL = "aria-label"
