// packages/ui/spike/lit/src/components/dropdown/UIDropdown.ts
import { html, nothing, type PropertyValues, type TemplateResult } from "lit"
import { state } from "lit/decorators.js"
import { ifDefined } from "lit/directives/if-defined.js"
import { live } from "lit/directives/live.js"
import { repeat } from "lit/directives/repeat.js"

import {
  proto,
  Converters,
  type FieldValue,
  type MenuAddition,
  type MenuOption,
  Shorthand,
  type OverlayEntry,
  DROPDOWN_ANCHOR_PROPERTY,
  type DropdownChangeDetail,
  type DropdownItemDetail,
  type DropdownOpenDetail,
  type DropdownOptions,
  type DropdownSearchDetail,
  type DropdownValue,
  IconRenderer,
  UIElement
} from "../../core"
import { FormElement, MenuOptions } from "../../forms"
import { buttonVocabulary } from "$/components/button/button.vocabulary.en"
import { dropdownVocabulary } from "$/components/dropdown/dropdown.vocabulary.en"
import { DropdownFallback } from "$/components/dropdown/dropdown.fallback"

import { type MenuEntry, UIItem } from "./UIItem"

import buttonCSS from "$/components/button/button.css?inline"
import dropdownCSS from "$/components/dropdown/dropdown.css?inline"

/****************
 * ### `<ui-dropdown>`
 * Combobox + listbox, in the markup contract of `dropdown.css`:  labels, `input.search`, `.sizer`,
 * `button.trigger`, `.text`, `button.remove.icon`, `.dropdown.icon`, then `.menu[role=listbox][popover]`.
 * - Model:  slotted `<ui-item>`s (read from light DOM on `slotchange` / `MutationObserver`) then the `options`
 *   property, filtered through `MenuOptions` (`excludeSelected` => `filter` => `withAdditions`) per keystroke.
 * - Menu:  `popover="manual"`, anchor-positioned (`--ui-dropdown-anchor` set inline to a per-instance ident),
 *   registered with `UI.overlays` for Escape / outside click.  Items render only while open, keyed by value.
 * - Controlled:  `value` and `open` change through `transition()` -- `ui-change` / `ui-open` / `ui-close`
 *   first;  a cancelled event or a host write from the handler wins.
 * - Form-associated (`FormElement`):  `multiple` submits one entry per value.
 * - Keyboard:  APG combobox.  Select-only (`button.trigger`):  arrows / Home / End / PageUp / PageDown,
 *   Enter / Space choose, type-ahead.  Editable (`search`):  typing filters, arrows move, Enter chooses,
 *   Backspace on an empty query removes the last label.  Escape comes from `UI.overlays`.
 ****************/
export class UIDropdown extends FormElement.for<
  typeof FormElement,
  typeof dropdownVocabulary,
  { value: DropdownValue | undefined; options: DropdownOptions | undefined }
>(dropdownVocabulary) {
  @proto static delegatesFocus = true
  @proto static Fallback = DropdownFallback
  @proto static forwardsAriaLabel = true
  @proto static sheets = [
    [buttonVocabulary.noun, buttonCSS],
    [dropdownVocabulary.noun, dropdownCSS]
  ] as const

  /** Search query (`search`). */
  @state() accessor query = ""

  /** Keyboard-highlighted index into `visible.options`, `-1` for none. */
  @state() accessor highlighted = -1

  /** Entries read from child `<ui-item>`s. */
  @state() accessor entries: readonly MenuEntry[] = []

  /** Options created by `allow-additions`, so a chosen addition keeps its text. */
  private added: MenuOption[] = []

  /** Every option, in order:  items, then `options`, then additions. */
  private all: MenuOptions = new MenuOptions()

  /** `all` by value. */
  private byValue = new Map<string, MenuOption>()

  /** Stable id suffix per option, for `aria-activedescendant`. */
  private ordinals = new Map<MenuOption, number>()

  /** What the menu lists right now. */
  private visible: MenuOptions = new MenuOptions()

  /** Value at first render, for `formResetCallback()`. */
  private defaultValue: DropdownValue | undefined

  /** Ids, assigned on first render (the runtime is in by then). */
  private ids?: { anchor: string; menu: string; text: string }

  /** Type-ahead buffer and its reset timer. */
  private typed = ""
  private typedTimer?: ReturnType<typeof setTimeout>

  /** Items (and slotted parts) changed. */
  private readonly observer = new MutationObserver(() => this.readItems())

  /** icon templates */
  private readonly icons = new IconRenderer(this)

  /** `UI.overlays` entry while open. */
  private readonly overlay: OverlayEntry = {
    element: this,
    kind: "popover",
    restoreFocus: false,
    onDismiss: () => this.closeMenu()
  }

  constructor() {
    super()
    this.addEventListener("focusout", this.onFocusOut)
  }

  override connectedCallback() {
    super.connectedCallback()
    this.observer.observe(this, { childList: true, subtree: true, attributes: true, characterData: true })
    this.readItems()
  }

  override disconnectedCallback() {
    super.disconnectedCallback()
    this.observer.disconnect()
    UIElement.runtime?.overlays.close(this.overlay)
  }

  ////////////////
  // ## Values
  ////////////////

  /** Chosen values as an array, whatever shape `value` has. */
  get values(): string[] {
    const { value } = this
    if (Array.isArray(value)) return [...(value as readonly string[])]
    if (!value) return []
    return this.multiple ? Converters.list(value) : [value]
  }

  /** Option for `value`, including additions. */
  optionFor(value: string): MenuOption | undefined {
    return this.byValue.get(value)
  }

  /** Disabled by attribute or by an ancestor fieldset. */
  private get locked(): boolean {
    return this.isDisabled || this.readonly
  }

  protected override formValue(): FieldValue {
    return this.multiple ? this.values : (this.values[0] ?? "")
  }

  protected override validationAnchor(): HTMLElement | undefined {
    return this.combobox() ?? undefined
  }

  override formResetCallback() {
    this.value = this.defaultValue
    this.query = ""
  }

  ////////////////
  // ## Model
  ////////////////

  /** Re-read child items. */
  private readItems() {
    const entries: MenuEntry[] = []
    for (const child of this.children) {
      if (child.slot) continue
      const entry = UIItem.entryOf(child)
      if (entry) entries.push(entry)
    }
    this.entries = entries
  }

  protected override willUpdate(changed: PropertyValues) {
    super.willUpdate(changed)
    if (changed.has("entries") || changed.has("options")) this.buildModel()
    if (changed.has("open") && !this.open) {
      this.query = ""
      this.highlighted = -1
    }
    this.visible = this.filtered()
    if (changed.has("open") && this.open && this.highlighted < 0) this.highlighted = this.defaultHighlight()
    if (this.highlighted >= this.visible.length) this.highlighted = this.visible.length - 1
    this.setState("open", this.open)
    this.setState("disabled", this.isDisabled)
    this.setState("loading", this.loading)
    this.setState("fluid", this.fluid)
  }

  /** Merge items, `options` and additions;  chosen items become the value if nothing else set one. */
  private buildModel() {
    const options: MenuOption[] = []
    for (const entry of this.entries) if (entry.option) options.push(entry.option)
    options.push(...(this.options ?? []), ...this.added)
    this.all = new MenuOptions(options)
    this.byValue = new Map(options.map((option) => [option.value, option]))
    this.ordinals = new Map(options.map((option, index) => [option, index]))
    if (!this.values.length) {
      const chosen = options.filter((option) => option.selected).map((option) => option.value)
      if (chosen.length) this.value = this.multiple ? chosen : chosen[0]
    }
  }

  /** `all` minus chosen labels, filtered by the query, plus the addition. */
  private filtered(): MenuOptions {
    let list = this.multiple ? this.all.excludeSelected(this.values) : this.all
    list = list.filter(this.query, { minCharacters: this.minCharacters })
    return list.withAdditions(this.query, { allowAdditions: this.allowAdditions, additionLabel: "" })
  }

  /** Highlight on open:  the chosen option, else the first enabled one. */
  private defaultHighlight(): number {
    const chosen = this.multiple ? -1 : this.visible.options.findIndex((option) => option.value === this.values[0])
    return chosen >= 0 ? chosen : this.visible.nextEnabledIndex(-1, 1)
  }

  ////////////////
  // ## Rendering
  ////////////////

  protected override render() {
    const ui = UIElement.runtime
    this.ids ??= ui
      ? { anchor: `--${ui.ids.next(ANCHOR_PREFIX)}`, menu: ui.ids.next(MENU_PREFIX), text: ui.ids.next(TEXT_PREFIX) }
      : undefined
    const ids = this.ids
    const classes = this.classes(undefined, { disabled: this.isDisabled })
    return html`<div
        class=${classes}
        style=${ids ? `${DROPDOWN_ANCHOR_PROPERTY}: ${ids.anchor}` : nothing}
        @click=${this.onRootClick}
      >
        ${this.multiple ? this.renderLabels() : nothing}${this.renderCombobox()}${
          this.labeled
            ? html`<span class="icon" part=${this.partName("icon")}>${this.icons.template(this.iconName())}</span>`
            : nothing
        }${this.renderText()}${
          this.clearable && this.values.length
            ? html`<button
                class="remove icon"
                part=${this.partName("clear")}
                type="button"
                tabindex="-1"
                aria-label=${this.t("clear")}
                @click=${this.onClear}
              ></button>`
            : nothing
        }<span class="dropdown icon" part=${this.partName("icon")}
          >${this.slotted("icon").length ? html`<slot name=${this.slotName("icon")}></slot>` : nothing}</span
        >${this.renderMenu()}
      </div>
      <slot hidden @slotchange=${this.onItemsSlotChange}></slot>`
  }

  /** `input.search` (+ `.sizer`) or `button.trigger`:  the combobox. */
  private renderCombobox() {
    const ids = this.ids
    const active =
      this.open && this.highlighted >= 0 ? this.optionId(this.visible.options[this.highlighted]) : undefined
    const name = this.accessibleName()
    if (this.search) {
      return html`<input
          class="search"
          part=${this.partName("search")}
          role="combobox"
          autocomplete="off"
          aria-autocomplete="list"
          aria-expanded=${String(this.open)}
          aria-controls=${ifDefined(ids?.menu)}
          aria-activedescendant=${ifDefined(active)}
          aria-label=${ifDefined(name)}
          aria-labelledby=${ifDefined(name ? undefined : ids?.text)}
          aria-required=${ifDefined(this.required ? "true" : undefined)}
          aria-busy=${ifDefined(this.loading ? "true" : undefined)}
          ?disabled=${this.isDisabled}
          ?readonly=${this.readonly}
          .value=${live(this.query)}
          @input=${this.onInput}
          @keydown=${this.onKeyDown}
        />${this.multiple ? html`<span class="sizer" aria-hidden="true">${this.query}</span>` : nothing}`
    }
    return html`<button
      class="trigger"
      part=${this.partName("trigger")}
      type="button"
      role="combobox"
      aria-haspopup="listbox"
      aria-expanded=${String(this.open)}
      aria-controls=${ifDefined(ids?.menu)}
      aria-activedescendant=${ifDefined(active)}
      aria-label=${ifDefined(name)}
      aria-labelledby=${ifDefined(name ? undefined : ids?.text)}
      aria-required=${ifDefined(this.required ? "true" : undefined)}
      aria-readonly=${ifDefined(this.readonly ? "true" : undefined)}
      aria-busy=${ifDefined(this.loading ? "true" : undefined)}
      ?disabled=${this.isDisabled}
      @click=${this.onTriggerClick}
      @keydown=${this.onKeyDown}
    ></button>`
  }

  /** Chosen values as removable labels (`multiple`). */
  private renderLabels() {
    return repeat(
      this.values,
      (value) => value,
      (value) => {
        const text = this.optionFor(value)?.text ?? value
        return html`<span class="ui label" part=${this.partName("label")}
          >${text}<button
            class="delete icon"
            type="button"
            tabindex="-1"
            aria-label=${`${this.t("clear")} ${text}`}
            @click=${(event: MouseEvent) => this.removeValue(value, event)}
          ></button
        ></span>`
      }
    )
  }

  /**
   * `.text`:  current value (with its icon / image / flag), else `text`, else the placeholder (`default`).
   * - `multiple` always shows the placeholder here, as Fomantic:  CSS hides it behind the labels.
   * - HACK: the content is NOT fallback content of the `trigger` slot (`dropdown.css` sizes
   *   `.text > img` / `.text > .icon`, which fallback content inside `<slot>` never matches);  the slot is
   *   rendered only when something is slotted into it.
   */
  private renderText() {
    const option = this.multiple ? undefined : this.optionFor(this.values[0] ?? "")
    const empty = !this.values.length
    const placeholder = this.multiple || (empty && this.text === undefined)
    const filtered = this.search && this.query !== ""
    const classes = `${placeholder ? "default " : ""}${filtered ? "filtered " : ""}text`
    const content = placeholder
      ? (this.placeholder ?? "")
      : option
        ? html`${this.renderDecorations(option)}${option.text}`
        : (this.text ?? this.values[0])
    const slotted = this.slotted("trigger").length > 0
    return html`<span class=${classes} part=${this.partName("text")} id=${ifDefined(this.ids?.text)}
      >${slotted ? html`<slot name=${this.slotName("trigger")}></slot>` : content}</span
    >`
  }

  /** The listbox popover;  items only while open (or when `simple` keeps it in the page). */
  private renderMenu() {
    const shown = this.open || this.simple
    const classes = this.direction === DIRECTION_LEFT ? "left menu" : "menu"
    return html`<div
      class=${classes}
      role="listbox"
      part=${this.partName("menu")}
      id=${ifDefined(this.ids?.menu)}
      popover=${this.simple ? nothing : "manual"}
      aria-multiselectable=${ifDefined(this.multiple ? "true" : undefined)}
      aria-label=${ifDefined(this.accessibleName())}
      @mousedown=${this.onMenuMouseDown}
      @click=${this.onMenuClick}
    >
      <slot name=${this.slotName("header")}></slot>${shown ? this.renderRows() : nothing}${
        shown && !this.visible.length
          ? html`<div class="message" role="option" aria-disabled="true" aria-selected="false">
              ${this.noResultsText ?? this.t("noResults")}
            </div>`
          : nothing
      }
    </div>`
  }

  /** Items, plus headers / dividers while nothing filters them. */
  private renderRows() {
    const rows: Row[] = []
    const indexes = new Map<MenuOption, number>()
    this.visible.options.forEach((option, index) => indexes.set(option, index))
    if (this.query) {
      for (const [index, option] of this.visible.options.entries()) rows.push({ key: option.value, option, index })
    } else {
      const addition = this.visible.addition
      if (addition) rows.push({ key: ADDITION_KEY, option: addition, index: indexes.get(addition)! })
      for (const [position, entry] of this.entries.entries()) {
        if (entry.option) {
          const index = indexes.get(entry.option)
          if (index !== undefined) rows.push({ key: entry.option.value, option: entry.option, index })
        } else rows.push({ key: `${entry.type}:${position}`, entry })
      }
      for (const option of [...(this.options ?? []), ...this.added]) {
        const index = indexes.get(option)
        if (index !== undefined) rows.push({ key: option.value, option, index })
      }
    }
    return repeat(
      rows,
      (row) => row.key,
      (row) => (row.option ? this.renderOption(row.option, row.index!) : this.renderEntry(row.entry!))
    )
  }

  /** One `.item[role=option]`. */
  private renderOption(option: MenuOption | MenuAddition, index: number): TemplateResult {
    const addition = "addition" in option
    const chosen = !addition && this.values.includes(option.value)
    const highlight = index === this.highlighted
    const classes = `${chosen ? "active " : ""}${highlight ? "selected " : ""}${option.disabled ? "disabled " : ""}${addition ? "addition " : ""}item`
    return html`<div
      class=${classes}
      role="option"
      part=${this.partName("item")}
      id=${this.optionId(option)}
      data-index=${index}
      aria-selected=${chosen ? "true" : "false"}
      aria-disabled=${ifDefined(option.disabled ? "true" : undefined)}
    >
      ${addition ? this.renderAddition(option.value) : this.renderOptionContent(option)}
    </div>`
  }

  /** Icon / image / flag, description, then the text with `<mark>`ed matches. */
  private renderOptionContent(option: MenuOption) {
    const description = option.description ? html`<span class="description">${option.description}</span>` : nothing
    return html`${this.renderDecorations(option)}${description}<span class="text"
        >${this.query ? this.highlight(option) : option.text}</span
      >`
  }

  /** `.icon`, `img.image` and `.flag` before an option's text. */
  private renderDecorations(option: MenuOption) {
    const icon = Shorthand.resolve(option.icon as never, Shorthand.map.name)?.name
    const image = Shorthand.resolve(option.image as never, Shorthand.map.src)?.src
    const flag = typeof option.flag === "string" ? UIDropdown.flagEmoji(option.flag) : undefined
    return html`${typeof icon === "string" ? html`<span class="icon">${this.icons.template(icon)}</span>` : nothing}${
      typeof image === "string" ? html`<img class="ui avatar image" src=${image} alt="" />` : nothing
    }${flag ? html`<span class="flag">${flag}</span>` : nothing}`
  }

  /** "Add <b>query</b>", from `addition-text` or the `addItem` text. */
  private renderAddition(value: string) {
    const template = this.additionText ?? this.t("addItem")
    const [before, after = ""] = template.split(VALUE_PLACEHOLDER)
    return html`${before}<b>${value}</b>${after}`
  }

  /** A header or divider. */
  private renderEntry(entry: MenuEntry) {
    if (entry.type === DIVIDER) return html`<hr class="divider" role="none" />`
    return html`<div class="header" role="presentation">${entry.text}</div>`
  }

  /** `option.text` with every matched range in `<mark>`. */
  private highlight(option: MenuOption) {
    const ranges = this.visible.highlights(option, this.query)
    if (!ranges.length) return option.text
    const parts: (string | TemplateResult)[] = []
    let at = 0
    for (const [start, end] of ranges) {
      parts.push(option.text.slice(at, start), html`<mark>${option.text.slice(start, end)}</mark>`)
      at = end
    }
    parts.push(option.text.slice(at))
    return parts
  }

  protected override updated(changed: PropertyValues) {
    super.updated(changed)
    if (this.defaultValue === undefined && !this.hasUpdatedOnce) {
      this.hasUpdatedOnce = true
      this.defaultValue = this.value
    }
    if (changed.has("open")) this.syncPopover()
    if (changed.has("highlighted") && this.open) {
      this.renderRoot.querySelector(".menu > .selected.item")?.scrollIntoView({ block: "nearest" })
    }
  }

  /** First `updated()` seen, so `defaultValue` is captured once. */
  private hasUpdatedOnce = false

  /** Show / hide the popover and (un)register with `UI.overlays` to match `open`. */
  private syncPopover() {
    const menu = this.menu()
    const ui = UIElement.runtime
    if (!menu || !ui || this.simple) return
    if (this.open && this.isConnected) {
      if (!menu.matches(":popover-open")) menu.showPopover()
      ui.overlays.open(this.overlay)
    } else {
      if (menu.matches(":popover-open")) menu.hidePopover()
      ui.overlays.close(this.overlay)
    }
  }

  ////////////////
  // ## Actions
  ////////////////

  /** Open, unless `ui-open` is cancelled. */
  openMenu(originalEvent?: Event) {
    if (this.open || this.locked) return
    const detail: DropdownOpenDetail = { open: true, originalEvent }
    this.transition("open", true, "ui-open", detail, { cancelable: true })
  }

  /** Close, unless `ui-close` is cancelled. */
  closeMenu(originalEvent?: Event) {
    if (!this.open) return
    const detail: DropdownOpenDetail = { open: false, originalEvent }
    this.transition("open", false, "ui-close", detail, { cancelable: true })
  }

  /** Choose `option`:  replaces the value, or adds a label with `multiple`. */
  select(option: MenuOption | MenuAddition, originalEvent?: Event) {
    if (option.disabled || this.locked) return
    const value = option.value
    const values = this.values
    if (this.multiple && this.maxSelections !== undefined && values.length >= this.maxSelections) return
    if ("addition" in option && !this.byValue.has(value)) {
      this.added = [...this.added, { value, text: option.text }]
      this.buildModel()
    }
    const add: DropdownItemDetail = { value, originalEvent }
    if (this.multiple || "addition" in option) this.emit("ui-add", add)
    const next: DropdownValue = this.multiple ? [...values, value] : value
    if (!this.multiple || !values.includes(value)) this.change(next, originalEvent)
    this.query = ""
    if (!this.multiple) this.closeMenu(originalEvent)
  }

  /** Remove `value` from a `multiple` dropdown. */
  removeValue(value: string, originalEvent?: Event) {
    if (this.locked) return
    const detail: DropdownItemDetail = { value, originalEvent }
    this.emit("ui-remove", detail)
    this.change(
      this.values.filter((item) => item !== value),
      originalEvent
    )
  }

  /** Clear every value. */
  clear(originalEvent?: Event) {
    if (this.locked || !this.values.length) return
    this.change(this.multiple ? [] : "", originalEvent)
  }

  /** `ui-change`, then the new value unless the host set one in its handler. */
  private change(value: DropdownValue, originalEvent?: Event) {
    const detail: DropdownChangeDetail = { value, originalEvent }
    this.transition("value", value, "ui-change", detail)
  }

  /** Move the highlight by `delta` enabled options. */
  private move(delta: number) {
    const next = this.visible.nextEnabledIndex(this.highlighted, delta)
    if (next >= 0) this.highlighted = next
  }

  ////////////////
  // ## Events
  ////////////////

  private readonly onItemsSlotChange = () => this.readItems()

  private readonly onTriggerClick = (event: MouseEvent) => {
    if (this.open) this.closeMenu(event)
    else this.openMenu(event)
  }

  /** Clicks on the box around a search input focus it and open. */
  private readonly onRootClick = (event: MouseEvent) => {
    if (!this.search || this.locked) return
    const input = this.combobox()
    if (event.composedPath()[0] !== input) input?.focus()
    this.openMenu(event)
  }

  private readonly onClear = (event: MouseEvent) => {
    event.stopPropagation()
    this.clear(event)
  }

  /** Keep focus on the combobox while clicking the menu. */
  private readonly onMenuMouseDown = (event: MouseEvent) => event.preventDefault()

  /** Delegated option clicks. */
  private readonly onMenuClick = (event: MouseEvent) => {
    event.stopPropagation()
    const item = (event.target as Element).closest?.(`[${INDEX_ATTRIBUTE}]`)
    const index = Number(item?.getAttribute(INDEX_ATTRIBUTE) ?? -1)
    const option = this.visible.options[index]
    if (option) this.select(option, event)
  }

  private readonly onInput = (event: Event) => {
    this.query = (event.target as HTMLInputElement).value
    const detail: DropdownSearchDetail = { query: this.query, originalEvent: event }
    this.emit("ui-search", detail)
    this.openMenu(event)
    this.visible = this.filtered()
    this.highlighted = this.visible.nextEnabledIndex(-1, 1)
  }

  /** Focus left the element (and its shadow root):  close. */
  private readonly onFocusOut = (event: FocusEvent) => {
    const next = event.relatedTarget as Node | null
    if (next && (next === this || this.contains(next))) return
    this.closeMenu(event)
  }

  /** The combobox keyboard pattern -- see class docs. */
  private readonly onKeyDown = (event: KeyboardEvent) => {
    if (event.defaultPrevented || this.locked || event.isComposing) return
    const { open } = this
    switch (event.key) {
      case "ArrowDown":
      case "ArrowUp": {
        if (!open) this.openMenu(event)
        else if (event.altKey && event.key === "ArrowUp") this.closeMenu(event)
        else this.move(event.key === "ArrowDown" ? 1 : -1)
        break
      }
      case "Home":
      case "End":
        if (this.search) return
        if (!open) this.openMenu(event)
        this.highlighted =
          event.key === "Home" ? this.visible.nextEnabledIndex(-1, 1) : this.visible.nextEnabledIndex(-1, -1)
        break
      case "PageDown":
      case "PageUp":
        if (!open) return
        this.move(event.key === "PageDown" ? PAGE_STEP : -PAGE_STEP)
        break
      case "Enter":
        if (open && this.highlighted >= 0) this.select(this.visible.options[this.highlighted]!, event)
        else if (!open && !this.search) this.openMenu(event)
        else return
        break
      case " ":
        if (this.search) return
        if (open && this.highlighted >= 0) this.select(this.visible.options[this.highlighted]!, event)
        else this.openMenu(event)
        break
      case "Tab":
        this.closeMenu(event)
        return
      case "Backspace":
        if (!this.multiple || !this.search || this.query || !this.values.length) return
        this.removeValue(this.values.at(-1)!, event)
        break
      default:
        if (this.search || event.key.length !== 1 || event.ctrlKey || event.metaKey || event.altKey) return
        this.typeAhead(event)
    }
    event.preventDefault()
  }

  /** Select-only type-ahead:  highlight the next option starting with the typed characters. */
  private typeAhead(event: KeyboardEvent) {
    clearTimeout(this.typedTimer)
    this.typed += event.key
    this.typedTimer = setTimeout(() => (this.typed = ""), TYPE_AHEAD_MS)
    const index = this.visible.selectionForKey(this.typed, this.highlighted)
    if (index < 0) return
    this.openMenu(event)
    this.highlighted = index
  }

  ////////////////
  // ## Helpers
  ////////////////

  /** The combobox element:  `input.search` or `button.trigger`. */
  private combobox(): HTMLElement | null {
    return this.renderRoot?.querySelector?.<HTMLElement>(this.search ? "input.search" : "button.trigger") ?? null
  }

  /** The listbox. */
  private menu(): HTMLElement | null {
    return this.renderRoot?.querySelector?.<HTMLElement>(".menu") ?? null
  }

  /** `aria-activedescendant` id of `option`. */
  private optionId(option: MenuOption | undefined): string | undefined {
    if (!option || !this.ids) return undefined
    return "addition" in option ? `${this.ids.menu}-add` : `${this.ids.menu}-${this.ordinals.get(option) ?? 0}`
  }

  /** Combobox name:  host `aria-label`, else `<label for>` text, else the placeholder. */
  private accessibleName(): string | undefined {
    const own = this.ariaLabelled()
    if (own) return own
    // SSR:  the shim's `ElementInternals` has no `labels`
    const labels = [...(this.internals.labels ?? [])].map((label) => label.textContent?.trim()).filter(Boolean)
    return labels.length ? labels.join(" ") : this.placeholder || undefined
  }

  /** Icon name from the `icon` attribute (labeled dropdowns). */
  private iconName(): string | undefined {
    return this.icon || undefined
  }

  /** Two-letter country code => flag emoji (regional indicators);  anything else as-is. */
  private static flagEmoji(code: string): string {
    if (!/^[a-z]{2}$/i.test(code)) return code
    const upper = code.toUpperCase()
    return String.fromCodePoint(REGIONAL_A + upper.charCodeAt(0) - 65, REGIONAL_A + upper.charCodeAt(1) - 65)
  }
}

/** One rendered row of the menu. */
type Row = {
  key: string
  option?: MenuOption | MenuAddition
  /** index into `visible.options` */
  index?: number
  entry?: MenuEntry
}
/** `data-*` attribute carrying an option's index, read by the delegated click handler. */
const INDEX_ATTRIBUTE = "data-index"
/** `UI.ids` prefixes. */
const ANCHOR_PREFIX = "ui-dropdown"
const MENU_PREFIX = "ui-dropdown-menu"
const TEXT_PREFIX = "ui-dropdown-text"
/** `repeat()` key of the addition row. */
const ADDITION_KEY = "\u0000addition"
/** `direction` value that right-aligns the menu (`.left.menu`). */
const DIRECTION_LEFT = "left"
/** `<ui-item type>` of a divider. */
const DIVIDER = "divider"
/** Placeholder in the `addItem` text. */
const VALUE_PLACEHOLDER = "{value}"
/** Options PageUp / PageDown move. */
const PAGE_STEP = 10
/** Type-ahead buffer lifetime. */
const TYPE_AHEAD_MS = 500
/** U+1F1E6 REGIONAL INDICATOR SYMBOL LETTER A. */
const REGIONAL_A = 0x1f1e6

// packages/ui/src/components/dropdown/UIDropdown.tsx
import { For, Show, createEffect, createMemo, untrack } from "solid-js"
import type { JSX } from "@solidjs/web"

import {
  Cell,
  Converters,
  DROPDOWN_ANCHOR_PROPERTY,
  Icons,
  proto,
  SlotContent,
  UI,
  type AttributeName,
  type DropdownOptions,
  type FieldValue,
  type MenuAddition,
  type MenuEntry,
  type MenuOption,
  type MenuSeparator,
  type OverlayEntry,
  type ValidationRule
} from "$/core"
import { FormElement, MenuOptions } from "$/forms"

import { dropdownVocabulary } from "./dropdown.vocabulary.en"
import { DropdownFallback } from "./dropdown.fallback"
import { SlottedItems } from "./SlottedItems"

import buttonCSS from "$/components/button/button.css?inline"
import dropdownCSS from "./dropdown.css?inline"

/** Vocabulary type, for brevity. */
type Vocabulary = typeof dropdownVocabulary

/****************
 * ### `<ui-dropdown>`
 * A combobox + listbox:  a `<button>` (or, with `search`, an `<input>`) combobox and an anchor-positioned
 * popover menu, both in the shadow root.
 * - Model:  slotted `<ui-item>`s (`SlottedItems`) + the `options` property + additions, as `MenuOptions`;
 *   memos derive the visible list (exclude chosen, filter, additions) per keystroke.
 * - `value` and `open` are auto-controlled (`Controlled`):  events first, the host may veto / override.
 * - Menu rows render only while open (`<For>` keyed by option identity);  `aria-activedescendant` points at
 *   the highlighted row.  Escape and outside clicks come from `UI.overlays`.
 * - Form-associated:  `multiple` submits one `FormData` entry per value;  `required` => `valueMissing`.
 ****************/
export class UIDropdown extends FormElement<Vocabulary> {
  @proto static vocabulary = dropdownVocabulary
  @proto static styles = { button: buttonCSS, dropdown: dropdownCSS }
  @proto static Fallback = DropdownFallback

  /** Rows PageUp / PageDown move. */
  static pageSize = 10

  /** Type-ahead buffer timeout, ms. */
  static typeAheadDelay = 500

  ////////////////
  // ## State
  ////////////////

  /** Options from slotted `<ui-item>`s. */
  readonly items = new SlottedItems(this.host)

  /** Light-DOM slot occupancy (`icon`, `trigger`, `header`). */
  readonly slots = new SlotContent(this.host)

  /** Values added with `allow-additions`, as options. */
  readonly added = new Cell<readonly MenuOption[]>([])

  /** Search query. */
  readonly query = new Cell("")

  /** Highlighted index into `visible().options`;  `-1` for none. */
  readonly active = new Cell(-1)

  /** `open`:  host-controlled, or internal. */
  readonly openState = this.controlled("open", false)

  /** `value`:  host-controlled, or internal;  starts from `selected` items. */
  readonly valueState = this.controlled("value", this.selectedItemValues() as never)

  /** Host value to restore on form reset (`undefined`:  back to the `selected` items). */
  private readonly initialValue = untrack(() => this.attrs.value)

  /** Search-key cache shared by every `MenuOptions` this element derives. */
  private readonly keys = new WeakMap() as NonNullable<ConstructorParameters<typeof MenuOptions>[2]>

  /** Stable DOM id per option. */
  private readonly optionIds = new WeakMap<MenuOption, string>()

  /** Type-ahead buffer and its timer. */
  private typed = ""
  private typedTimer?: ReturnType<typeof setTimeout>

  /** Ids / anchor name, from `UI.ids` once rendering. */
  private ids = { menu: "", text: "", anchor: "" }

  /** The combobox (trigger button or search input), and the menu. */
  private combobox?: HTMLElement
  private menu?: HTMLElement

  /** This element's `UI.overlays` entry. */
  private readonly overlay: OverlayEntry = {
    element: this.host,
    kind: "popover",
    restoreFocus: false,
    onDismiss: () => void this.setOpen(false)
  }

  ////////////////
  // ## Derived
  ////////////////

  /** `options` property, validated to an array. */
  readonly propOptions = createMemo((): DropdownOptions => {
    const options = this.attrs.options
    return Array.isArray(options) ? (options as DropdownOptions) : []
  })

  /** Every option:  slotted, then `options`, then additions. */
  readonly all = createMemo(
    (): readonly MenuOption[] => [...this.items.entries().filter(isOption), ...this.propOptions(), ...this.added.get()],
    { equals: sameItems }
  )

  /** Option by value, for texts of chosen values. */
  readonly byValue = createMemo(() => new Map(this.all().map((option) => [option.value, option])))

  /** Chosen values, always as an array. */
  readonly values = createMemo(
    (): readonly string[] => {
      const value = this.valueState.get() as unknown
      if (Array.isArray(value)) return value.map(String)
      if (typeof value !== "string" || value === "") return []
      return this.attrs.multiple ? Converters.list(value) : [value]
    },
    { equals: sameItems }
  )

  /** Chosen values as a set, for row state. */
  readonly chosen = createMemo(() => new Set(this.values()))

  /** The effective query:  only with `search`. */
  readonly effectiveQuery = createMemo(() => (this.attrs.search ? this.query.get() : ""))

  /** Options offered now:  minus chosen (multiple), filtered, plus the addition. */
  readonly visible = createMemo(() => {
    const query = this.effectiveQuery()
    return new MenuOptions(this.all(), undefined, this.keys)
      .excludeSelected(this.attrs.multiple ? this.values() : [])
      .filter(query, { minCharacters: this.attrs.minCharacters ?? 0 })
      .withAdditions(query, { allowAdditions: this.attrs.allowAdditions && this.canAdd() })
  })

  /** Menu rows:  separators in place while not searching, else just the visible options. */
  readonly rows = createMemo(
    (): readonly (MenuEntry | MenuAddition)[] => {
      const visible = this.visible()
      const entries = this.items.entries()
      if (this.effectiveQuery() || !entries.some((entry) => "type" in entry)) return visible.options
      const shown = new Set<MenuOption>(visible.options)
      const rows: (MenuEntry | MenuAddition)[] = entries.filter((entry) => "type" in entry || shown.has(entry))
      const slotted = new Set<MenuEntry>(entries)
      for (const option of visible.options) if (!slotted.has(option)) rows.push(option)
      return rows
    },
    { equals: sameItems }
  )

  /** Highlighted option. */
  readonly highlighted = createMemo(() => this.visible().options[this.active.get()] as MenuOption | undefined)

  /** Open now. */
  isOpen(): boolean {
    return this.openState.get()
  }

  isDisabled(): boolean {
    return this.attrs.disabled || this.formDisabled.get()
  }

  /** Label for the combobox and listbox:  `placeholder`, else `text`, else `name`. */
  private label(): string {
    return this.attrs.placeholder ?? this.attrs.text ?? this.attrs.name ?? ""
  }

  /** Text of `value`:  its option's, else `text` (single), else the value itself. */
  private textOf(value: string): string {
    return this.byValue().get(value)?.text ?? (this.attrs.multiple ? undefined : this.attrs.text) ?? value
  }

  /** Room for another value? */
  private canAdd(): boolean {
    const max = this.attrs.maxSelections
    return !this.attrs.multiple || max === undefined || this.values().length < max
  }

  ////////////////
  // ## Element hooks
  ////////////////

  protected classValue(name: AttributeName<Vocabulary>): unknown {
    if (name === "open") return this.isOpen()
    if (name === "disabled") return this.isDisabled()
    return super.classValue(name)
  }

  protected hostStates() {
    return {
      open: this.isOpen(),
      disabled: this.isDisabled(),
      loading: this.attrs.loading,
      fluid: this.attrs.fluid
    }
  }

  formValue(): FieldValue {
    const values = this.values()
    return this.attrs.multiple ? values : (values[0] ?? null)
  }

  protected formName(): string | undefined {
    return this.attrs.name
  }

  formReset() {
    this.valueState.set(this.initialValue as never)
    this.query.set("")
  }

  protected rules(): ValidationRule[] {
    return this.attrs.required ? [REQUIRED_RULE] : []
  }

  protected validationLabel(): string | undefined {
    return this.label() || undefined
  }

  protected validationAnchor(): HTMLElement | undefined {
    return this.combobox
  }

  ////////////////
  // ## Rendering
  ////////////////

  render(): JSX.Element {
    this.ids = { menu: UI.ids.next(ID_PREFIX), text: UI.ids.next(ID_PREFIX), anchor: `--${UI.ids.next(ID_PREFIX)}` }
    this.effects()
    return (
      <div class={this.classes()} style={{ [DROPDOWN_ANCHOR_PROPERTY]: this.ids.anchor }} onClick={this.onRootClick}>
        <Show when={this.attrs.multiple}>
          <For each={this.values()}>{(value) => this.chip(value)}</For>
        </Show>
        <Show when={this.attrs.search} fallback={this.trigger()}>
          {this.searchInput()}
          <Show when={this.attrs.multiple}>
            <span class="sizer" aria-hidden="true">
              {this.query.get()}
            </span>
          </Show>
        </Show>
        <Show when={this.attrs.labeled && this.attrs.icon}>{this.labeledIcon()}</Show>
        <span
          id={this.ids.text}
          class={[TEXT, { [DEFAULT]: this.showsPlaceholder(), [FILTERED]: !!this.effectiveQuery() }]}
          part={this.part("text")}
        >
          <slot name={this.slot("trigger")}>{this.displayText()}</slot>
        </span>
        <Show when={this.attrs.clearable && this.values().length && !this.attrs.readonly}>
          <button
            type="button"
            class="remove icon"
            part={this.part("clear")}
            aria-label={this.text("clear")}
            onClick={this.onClear}
          />
        </Show>
        <span class="dropdown icon" part={this.part("icon")}>
          <Show when={this.slots.has(this.slot("icon"))}>
            <slot name={this.slot("icon")} />
          </Show>
        </span>
        {this.menuElement()}
        <slot hidden />
      </div>
    )
  }

  /** Text shown in `.text`:  chosen text (single), else `text` (a menu's fixed label), else the placeholder. */
  private displayText(): string {
    const [first] = this.values()
    if (first !== undefined && !this.attrs.multiple) return this.textOf(first)
    return this.attrs.text ?? this.attrs.placeholder ?? ""
  }

  /** Showing the placeholder (grey `default` text)? */
  private showsPlaceholder(): boolean {
    return !this.values().length && this.attrs.text === undefined
  }

  /** Combobox ARIA shared by the trigger and the search input. */
  private comboboxProps() {
    return {
      role: "combobox",
      "aria-expanded": this.isOpen() ? "true" : "false",
      "aria-controls": this.ids.menu,
      "aria-haspopup": "listbox",
      "aria-activedescendant": this.isOpen() && this.highlighted() ? this.optionId(this.highlighted()!) : undefined,
      "aria-label": this.label() || undefined,
      "aria-describedby": this.ids.text,
      "aria-busy": this.attrs.loading ? "true" : undefined,
      "aria-readonly": this.attrs.readonly ? "true" : undefined,
      "aria-required": this.attrs.required ? "true" : undefined,
      "aria-invalid": this.validation().valid ? undefined : "true"
    } as const
  }

  /** The covering `<button>` combobox. */
  private trigger(): JSX.Element {
    return (
      <button
        ref={(element) => (this.combobox = element)}
        type="button"
        class="trigger"
        part={this.part("trigger")}
        disabled={this.isDisabled()}
        {...this.comboboxProps()}
        onClick={this.onTriggerClick}
        onKeyDown={this.onKeyDown}
        onBlur={this.onBlur}
      />
    )
  }

  /** The search `<input>` combobox. */
  private searchInput(): JSX.Element {
    return (
      <input
        ref={(element) => (this.combobox = element)}
        class="search"
        part={this.part("search")}
        autocomplete="off"
        aria-autocomplete="list"
        disabled={this.isDisabled()}
        readonly={this.attrs.readonly}
        value={this.query.get()}
        {...this.comboboxProps()}
        onInput={this.onInput}
        onClick={this.onTriggerClick}
        onKeyDown={this.onKeyDown}
        onBlur={this.onBlur}
      />
    )
  }

  /** A chosen value's label, with its delete button (multiple). */
  private chip(value: string): JSX.Element {
    return (
      <span class="ui label" part={this.part("label")}>
        {this.textOf(value)}
        <Show when={!this.attrs.readonly && !this.isDisabled()}>
          <button
            type="button"
            class="delete icon"
            tabindex="-1"
            aria-label={this.text("removeValue", { value: this.textOf(value) })}
            onClick={(event) => this.remove(value, event)}
          />
        </Show>
      </span>
    )
  }

  /** The icon block of a `labeled` (icon) dropdown button. */
  private labeledIcon(): JSX.Element {
    return <span class={ICON} ref={(element) => void SVGIcon.fill(element, this.attrs.icon)} />
  }

  /** The listbox popover. */
  private menuElement(): JSX.Element {
    return (
      <div
        ref={(element) => (this.menu = element)}
        id={this.ids.menu}
        class={[MENU, { [LEFT]: this.attrs.direction === "left" }]}
        role="listbox"
        popover={this.attrs.simple ? undefined : "manual"}
        part={this.part("menu")}
        aria-label={this.label() || undefined}
        aria-multiselectable={this.attrs.multiple ? "true" : undefined}
        onMouseDown={preventDefault}
      >
        <slot name={this.slot("header")} />
        <Show when={this.isOpen() || this.attrs.simple}>
          <For each={this.rows()}>{(row) => this.row(row)}</For>
          <Show when={!this.visible().length}>
            {/* an option (disabled) rather than a bare div:  a listbox must own options (axe `aria-required-children`) */}
            <div class="message" role="option" aria-disabled="true" aria-selected="false">
              {this.attrs.noResultsText ?? this.text("noResults")}
            </div>
          </Show>
        </Show>
      </div>
    )
  }

  /** One menu row. */
  private row(row: MenuEntry | MenuAddition): JSX.Element {
    if ("type" in row) return this.separator(row)
    if ("addition" in row) return this.additionRow(row)
    const option = row
    const slot = this.items.slots.get(option)
    return (
      <div
        id={this.optionId(option)}
        class={[
          ITEM,
          {
            [ACTIVE]: this.chosen().has(option.value),
            [SELECTED]: this.highlighted() === option,
            [DISABLED]: !!option.disabled
          }
        ]}
        role="option"
        part={this.part("item")}
        aria-selected={this.chosen().has(option.value) ? "true" : "false"}
        aria-disabled={option.disabled ? "true" : undefined}
        onPointerMove={() => this.highlight(option)}
        onClick={(event) => this.select(option, event)}
      >
        <Show when={slot} fallback={this.optionContent(option)}>
          <slot name={slot} />
        </Show>
      </div>
    )
  }

  /** Icon / image / flag, text with `<mark>`ed matches, description. */
  private optionContent(option: MenuOption): JSX.Element {
    return (
      <>
        <Show when={typeof option.icon === "string"}>
          <span class={ICON} ref={(element) => void SVGIcon.fill(element, option.icon as string)} />
        </Show>
        <Show when={typeof option.image === "string"}>
          <img class="ui avatar image" src={option.image as string} alt="" />
        </Show>
        <Show when={typeof option.flag === "string"}>
          <span class="flag">{flagEmoji(option.flag as string)}</span>
        </Show>
        <Show when={option.description}>
          <span class="description">{option.description}</span>
        </Show>
        <span class={TEXT}>{this.highlightText(option)}</span>
      </>
    )
  }

  /** `option.text` with the query's matches in `<mark>`. */
  private highlightText(option: MenuOption): JSX.Element {
    const query = this.effectiveQuery()
    if (!query) return option.text
    const ranges = this.visible().highlights(option, query)
    const parts: JSX.Element[] = []
    let at = 0
    for (const [start, end] of ranges) {
      if (start > at) parts.push(option.text.slice(at, start))
      parts.push(<mark>{option.text.slice(start, end)}</mark>)
      at = end
    }
    if (at < option.text.length) parts.push(option.text.slice(at))
    return parts
  }

  /** The "Add …" row of `allow-additions`. */
  private additionRow(option: MenuAddition): JSX.Element {
    const template = this.attrs.additionText ?? this.text("addItem")
    const [before = "", after = ""] = template.split(VALUE_PLACEHOLDER)
    return (
      <div
        id={this.optionId(option)}
        class={[ITEM, ADDITION, { [SELECTED]: this.highlighted() === option }]}
        role="option"
        part={this.part("item")}
        aria-selected="false"
        onPointerMove={() => this.highlight(option)}
        onClick={(event) => this.select(option, event)}
      >
        {before}
        <b>{option.text}</b>
        {after}
      </div>
    )
  }

  /** Header or divider row. */
  private separator(entry: MenuSeparator): JSX.Element {
    return entry.type === "divider" ? (
      <hr class="divider" role="presentation" />
    ) : (
      <div class="header" role="presentation">
        {entry.text}
      </div>
    )
  }

  /** Stable id for `option`'s row. */
  private optionId(option: MenuOption): string {
    let id = this.optionIds.get(option)
    if (!id) this.optionIds.set(option, (id = `${this.ids.menu}-${++optionCounter}`))
    return id
  }

  ////////////////
  // ## Effects
  ////////////////

  /**
   * Popover + overlay registration while open AND connected;  highlighted row kept in view.
   * - `connected`:  `keepAlive` keeps an open dropdown's state when it's removed, but the page must not keep its
   *   overlay entry (Escape / outside clicks) for an element that isn't there;  reconnecting re-registers.
   */
  private effects() {
    createEffect(
      () => this.isOpen() && this.connected.get(),
      (open) => {
        const { menu } = this
        if (!open || !menu || !menu.popover) return
        if (!menu.matches(POPOVER_OPEN)) menu.showPopover()
        UI.overlays.open(this.overlay)
        return () => {
          if (menu.matches(POPOVER_OPEN)) menu.hidePopover()
          UI.overlays.close(this.overlay)
        }
      }
    )
    createEffect(
      () => (this.isOpen() ? this.highlighted() : undefined),
      (option) => {
        if (option) this.host.renderRoot.getElementById(this.optionId(option))?.scrollIntoView({ block: "nearest" })
      }
    )
  }

  ////////////////
  // ## Transitions
  ////////////////

  /**
   * Open or close, dispatching the cancelable `ui-open` / `ui-close` first.
   * - Opening highlights the chosen option, else the first enabled one.
   */
  setOpen(open: boolean, originalEvent?: Event): boolean {
    if (open === untrack(() => this.isOpen())) return false
    if (open && (this.isDisabled() || this.attrs.readonly)) return false
    const done = this.openState.request(open, () => this.emit(open ? "ui-open" : "ui-close", { open, originalEvent }))
    if (done && open) {
      const options = untrack(() => this.visible())
      const chosen = options.options.findIndex((option) => untrack(() => this.chosen()).has(option.value))
      this.active.set(chosen >= 0 ? chosen : options.nextEnabledIndex(-1, 1))
    }
    if (done && !open) this.query.set("")
    return done
  }

  /** Choose `option` (or add the addition), as the user did with `originalEvent`. */
  select(option: MenuOption, originalEvent?: Event) {
    if (option.disabled || this.attrs.readonly) return
    const values = untrack(() => this.values())
    const addition = "addition" in option
    if (this.attrs.multiple) {
      if (!untrack(() => this.canAdd())) return
      const next = [...values, option.value]
      this.commit(next, originalEvent, () => this.emit("ui-add", { value: option.value, originalEvent }))
      this.query.set("")
      this.active.set(0)
    } else {
      this.commit([option.value], originalEvent, () => {
        if (addition) this.emit("ui-add", { value: option.value, originalEvent })
      })
      this.setOpen(false, originalEvent)
    }
    if (addition) this.added.set([...untrack(() => this.added.get()), { value: option.value, text: option.text }])
  }

  /** Remove one chosen value (multiple). */
  remove(value: string, originalEvent?: Event) {
    if (this.attrs.readonly || this.isDisabled()) return
    const next = untrack(() => this.values()).filter((item) => item !== value)
    this.commit(next, originalEvent, () => this.emit("ui-remove", { value, originalEvent }))
  }

  /**
   * Change the value to `next` through `Controlled`:  `announce()` (ui-add / ui-remove) and `ui-change` first.
   * - Returns true when applied.
   */
  private commit(next: readonly string[], originalEvent: Event | undefined, announce?: () => void): boolean {
    const value = this.attrs.multiple ? [...next] : (next[0] ?? "")
    return this.valueState.request(value as never, () => {
      announce?.()
      this.emit("ui-change", { value, originalEvent })
      return true
    })
  }

  /** Highlight `option` if it's visible. */
  private highlight(option: MenuOption) {
    const index = untrack(() => this.visible()).options.indexOf(option)
    if (index >= 0 && index !== untrack(() => this.active.get())) this.active.set(index)
  }

  /** Move the highlight by `delta` enabled options. */
  private move(delta: number) {
    const options = untrack(() => this.visible())
    this.active.set(
      options.nextEnabledIndex(
        untrack(() => this.active.get()),
        delta
      )
    )
  }

  ////////////////
  // ## Handlers
  ////////////////

  /** Trigger / input click:  toggle (the input only opens). */
  private readonly onTriggerClick = (event: MouseEvent) => {
    if (this.attrs.search && untrack(() => this.isOpen())) return
    this.setOpen(!untrack(() => this.isOpen()), event)
  }

  /** Click on the root outside the combobox (caret, text of a search dropdown):  focus + toggle. */
  private readonly onRootClick = (event: MouseEvent) => {
    const target = event.composedPath()[0]
    if (!this.attrs.search || target === this.combobox || this.menu?.contains(target as Node)) return
    if ((target as Element).closest?.("button")) return
    this.combobox?.focus()
    this.setOpen(!untrack(() => this.isOpen()), event)
  }

  /** Clear button. */
  private readonly onClear = (event: MouseEvent) => {
    event.stopPropagation()
    this.commit([], event)
  }

  /** Search typing:  filter, open, highlight the first match, `ui-search`. */
  private readonly onInput = (event: InputEvent) => {
    const query = (event.currentTarget as HTMLInputElement).value
    this.query.set(query)
    this.setOpen(true, event)
    this.active.set(0)
    this.emit("ui-search", { query, originalEvent: event })
  }

  /** Leaving the combobox closes the menu, unless focus stays inside. */
  private readonly onBlur = (event: FocusEvent) => {
    const next = event.relatedTarget as Node | null
    if (next && (this.host.contains(next) || this.host.renderRoot.contains(next))) return
    this.setOpen(false, event)
  }

  /** Combobox keyboard pattern (APG), plus type-ahead and Backspace-removes-last. */
  private readonly onKeyDown = (event: KeyboardEvent) => {
    if (this.isDisabled() || event.defaultPrevented) return
    const open = untrack(() => this.isOpen())
    const { key } = event
    switch (key) {
      case "ArrowDown":
      case "ArrowUp":
        event.preventDefault()
        if (!open) this.setOpen(true, event)
        else this.move(key === "ArrowDown" ? 1 : -1)
        return
      case "Home":
      case "End":
        if (!open) return
        event.preventDefault()
        this.active.set(untrack(() => this.visible()).nextEnabledIndex(-1, key === "Home" ? 1 : -1))
        return
      case "PageDown":
      case "PageUp":
        if (!open) return
        event.preventDefault()
        this.move(key === "PageDown" ? UIDropdown.pageSize : -UIDropdown.pageSize)
        return
      case "Enter": {
        if (!open) {
          if (this.attrs.search) this.setOpen(true, event)
          return
        }
        event.preventDefault()
        const visible = untrack(() => this.visible())
        const option = untrack(() => this.highlighted()) ?? visible.addition
        if (option) this.select(option, event)
        return
      }
      case " ":
        if (this.attrs.search || !open) return
        event.preventDefault()
        if (untrack(() => this.highlighted()))
          this.select(
            untrack(() => this.highlighted())!,
            event
          )
        return
      case "Tab":
        if (open) this.setOpen(false, event)
        return
      case "Backspace": {
        const values = untrack(() => this.values())
        if (this.attrs.search && this.attrs.multiple && !untrack(() => this.query.get()) && values.length) {
          this.remove(values.at(-1)!, event)
        }
        return
      }
    }
    if (!this.attrs.search && key.length === 1 && !event.ctrlKey && !event.metaKey && !event.altKey) {
      event.preventDefault()
      this.typeAhead(key, event)
    }
  }

  /** Type-ahead:  extend the buffer, highlight the next match (opening first if needed). */
  private typeAhead(key: string, event: KeyboardEvent) {
    clearTimeout(this.typedTimer)
    this.typed += key
    this.typedTimer = setTimeout(() => (this.typed = ""), UIDropdown.typeAheadDelay)
    if (!untrack(() => this.isOpen())) this.setOpen(true, event)
    const options = untrack(() => this.visible())
    const index = options.selectionForKey(
      this.typed,
      untrack(() => this.active.get())
    )
    if (index >= 0) this.active.set(index)
  }

  /** Values of slotted items marked `selected`, the uncontrolled starting value. */
  private selectedItemValues(): string | string[] | undefined {
    const values = untrack(() => this.items.entries())
      .filter(isOption)
      .filter((option) => option.selected)
      .map((option) => option.value)
    if (!values.length) return undefined
    return untrack(() => this.attrs.multiple) ? values : values[0]
  }
}

////////////////
// ## Helpers
////////////////

/**
 * Draws an `Icons` SVG into an element once its data has loaded.
 * - Plain DOM, no signal:  rows are many and their icons never change.
 */
class SVGIcon {
  /** Replace `element`'s content with icon `name`, when loaded. */
  static async fill(element: HTMLElement, name: string | undefined) {
    if (!name) return
    const data = Icons.peek(name) ?? (await Icons.get(name))
    if (data) element.replaceChildren(Icons.svg(data))
  }
}

/**
 * Same items in the same order?  Memo `equals` for arrays, so a recomputation that yields an equivalent list
 * doesn't wake every row (Solid's dev diagnostics flag it as `UNSTABLE_MEMO_OUTPUT`).
 */
function sameItems<T>(a: readonly T[], b: readonly T[]): boolean {
  return a.length === b.length && a.every((item, index) => item === b[index])
}

/** Is `entry` an option (not a separator)? */
function isOption(entry: MenuEntry): entry is MenuOption {
  return !("type" in entry)
}

/** `preventDefault()`:  menu presses must not take focus from the combobox. */
function preventDefault(event: Event) {
  event.preventDefault()
}

/** Country code => flag emoji (regional indicators), e.g. `fr` => 🇫🇷;  other text unchanged. */
function flagEmoji(code: string): string {
  if (!/^[a-z]{2}$/i.test(code)) return code
  const upper = code.toUpperCase()
  return String.fromCodePoint(REGIONAL_A + upper.charCodeAt(0) - 65, REGIONAL_A + upper.charCodeAt(1) - 65)
}

/** Counter behind option ids. */
let optionCounter = 0

/** Code point of the regional indicator for `A`. */
const REGIONAL_A = 0x1f1e6

/** `UI.ids` prefix. */
const ID_PREFIX = "ui-dropdown"

/** `required` => Fomantic's `notEmpty`. */
const REQUIRED_RULE: ValidationRule = "notEmpty"

/** Placeholder in the `addItem` text. */
const VALUE_PLACEHOLDER = "{value}"

/** Open popover pseudo-class. */
const POPOVER_OPEN = ":popover-open"

/**
 * Class words of the markup contract (`dropdown.css`) -- grammar, not attributes, so not in the vocabulary.
 * - NOTE: `active` === chosen, `selected` === highlighted:  Fomantic's meanings.
 */
const TEXT = "text"
const DEFAULT = "default"
const FILTERED = "filtered"
const MENU = "menu"
const LEFT = "left"
const ITEM = "item"
const ACTIVE = "active"
const SELECTED = "selected"
const DISABLED = "disabled"
const ADDITION = "addition"
const ICON = "icon"
